#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'CustomersWebServiceDriver.rb'


module Brink::Api

endpoint_url = ARGV.shift
obj = ICustomersWebService.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   authenticateCustomer(parameters)
#
# ARGS
#   parameters      AuthenticateCustomer - {http://tempuri.org/}AuthenticateCustomer
#
# RETURNS
#   parameters      AuthenticateCustomerResponse - {http://tempuri.org/}AuthenticateCustomerResponse
#
# RAISES
#   detail          AccessFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessFault
#   detail          LocationFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationFault
#
parameters = nil
puts obj.authenticateCustomer(parameters)

# SYNOPSIS
#   getCustomersByLastEditTime(parameters)
#
# ARGS
#   parameters      GetCustomersByLastEditTime - {http://tempuri.org/}GetCustomersByLastEditTime
#
# RETURNS
#   parameters      GetCustomersByLastEditTimeResponse - {http://tempuri.org/}GetCustomersByLastEditTimeResponse
#
# RAISES
#   detail          AccessFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessFault
#   detail          LocationFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationFault
#
parameters = nil
puts obj.getCustomersByLastEditTime(parameters)

# SYNOPSIS
#   getCustomer(parameters)
#
# ARGS
#   parameters      GetCustomer - {http://tempuri.org/}GetCustomer
#
# RETURNS
#   parameters      GetCustomerResponse - {http://tempuri.org/}GetCustomerResponse
#
# RAISES
#   detail          AccessFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessFault
#   detail          LocationFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationFault
#
parameters = nil
puts obj.getCustomer(parameters)

# SYNOPSIS
#   lookupCustomer(parameters)
#
# ARGS
#   parameters      LookupCustomer - {http://tempuri.org/}LookupCustomer
#
# RETURNS
#   parameters      LookupCustomerResponse - {http://tempuri.org/}LookupCustomerResponse
#
# RAISES
#   detail          AccessFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessFault
#   detail          LocationFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationFault
#
parameters = nil
puts obj.lookupCustomer(parameters)

# SYNOPSIS
#   saveCustomer(parameters)
#
# ARGS
#   parameters      SaveCustomer - {http://tempuri.org/}SaveCustomer
#
# RETURNS
#   parameters      SaveCustomerResponse - {http://tempuri.org/}SaveCustomerResponse
#
# RAISES
#   detail          AccessFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessFault
#   detail          DuplicateEmailAddressFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}DuplicateEmailAddressFault
#   detail          InvalidCardNumberFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}InvalidCardNumberFault
#   detail          InvalidPhoneNumberFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}InvalidPhoneNumberFault
#   detail          InvalidRequestFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}InvalidRequestFault
#   detail          LocationFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationFault
#
parameters = nil
puts obj.saveCustomer(parameters)

# SYNOPSIS
#   unsubscribeEmail(parameters)
#
# ARGS
#   parameters      UnsubscribeEmail - {http://tempuri.org/}UnsubscribeEmail
#
# RETURNS
#   parameters      UnsubscribeEmailResponse - {http://tempuri.org/}UnsubscribeEmailResponse
#
# RAISES
#   detail          AccessFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessFault
#   detail          LocationFault - {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationFault
#
parameters = nil
puts obj.unsubscribeEmail(parameters)




end
