# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'KitchenWebService.rb'
require 'soap/mapping'

module KitchenWebServiceMappingRegistry
  EncodedRegistry = ::SOAP::Mapping::EncodedRegistry.new
  LiteralRegistry = ::SOAP::Mapping::LiteralRegistry.new
  NsPosWebService = "http://schemas.datacontract.org/2004/07/Pos.Web.Service"
  NsSystem = "http://schemas.datacontract.org/2004/07/System"
  NsV1 = "http://www.brinksoftware.com/webservices/kitchen/v1"

  EncodedRegistry.register(
    :class => GetOrderBumpTimesRequest,
    :schema_type => XSD::QName.new(NsV1, "GetOrderBumpTimesRequest"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["businessDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV1, "BusinessDate")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => GetOrderBumpTimesReply,
    :schema_type => XSD::QName.new(NsV1, "GetOrderBumpTimesReply"),
    :schema_basetype => XSD::QName.new(NsPosWebService, "Reply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]],
      ["orderBumpTimes", ["ArrayOfOrderBumpTime", XSD::QName.new(NsV1, "OrderBumpTimes")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => ArrayOfOrderBumpTime,
    :schema_type => XSD::QName.new(NsV1, "ArrayOfOrderBumpTime"),
    :schema_element => [
      ["orderBumpTime", ["OrderBumpTime[]", XSD::QName.new(NsV1, "OrderBumpTime")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => OrderBumpTime,
    :schema_type => XSD::QName.new(NsV1, "OrderBumpTime"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["firstSendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "FirstSendTime")], [0, 1]],
      ["kitchenQueueId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "KitchenQueueId")], [0, 1]],
      ["orderId", ["SOAP::SOAPLong", XSD::QName.new(NsV1, "OrderId")], [0, 1]],
      ["sendNumber", ["SOAP::SOAPShort", XSD::QName.new(NsV1, "SendNumber")], [0, 1]],
      ["sendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "SendTime")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => GetOrderItemBumpTimesRequest,
    :schema_type => XSD::QName.new(NsV1, "GetOrderItemBumpTimesRequest"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["businessDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV1, "BusinessDate")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => GetOrderItemBumpTimesReply,
    :schema_type => XSD::QName.new(NsV1, "GetOrderItemBumpTimesReply"),
    :schema_basetype => XSD::QName.new(NsPosWebService, "Reply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]],
      ["orderItemBumpTimes", ["ArrayOfOrderItemBumpTime", XSD::QName.new(NsV1, "OrderItemBumpTimes")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => ArrayOfOrderItemBumpTime,
    :schema_type => XSD::QName.new(NsV1, "ArrayOfOrderItemBumpTime"),
    :schema_element => [
      ["orderItemBumpTime", ["OrderItemBumpTime[]", XSD::QName.new(NsV1, "OrderItemBumpTime")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => OrderItemBumpTime,
    :schema_type => XSD::QName.new(NsV1, "OrderItemBumpTime"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["fireTime", ["DateTimeOffset", XSD::QName.new(NsV1, "FireTime")], [0, 1]],
      ["kitchenQueueId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "KitchenQueueId")], [0, 1]],
      ["orderId", ["SOAP::SOAPLong", XSD::QName.new(NsV1, "OrderId")], [0, 1]],
      ["orderItemId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "OrderItemId")], [0, 1]],
      ["sendNumber", ["SOAP::SOAPShort", XSD::QName.new(NsV1, "SendNumber")], [0, 1]],
      ["sendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "SendTime")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => DateTimeOffset,
    :schema_type => XSD::QName.new(NsSystem, "DateTimeOffset"),
    :schema_element => [
      ["dateTime", ["SOAP::SOAPDateTime", XSD::QName.new(NsSystem, "DateTime")]],
      ["offsetMinutes", ["SOAP::SOAPShort", XSD::QName.new(NsSystem, "OffsetMinutes")]]
    ]
  )

  EncodedRegistry.register(
    :class => Reply,
    :schema_type => XSD::QName.new(NsPosWebService, "Reply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderBumpTimesRequest,
    :schema_type => XSD::QName.new(NsV1, "GetOrderBumpTimesRequest"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["businessDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV1, "BusinessDate")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderBumpTimesReply,
    :schema_type => XSD::QName.new(NsV1, "GetOrderBumpTimesReply"),
    :schema_basetype => XSD::QName.new(NsPosWebService, "Reply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]],
      ["orderBumpTimes", ["ArrayOfOrderBumpTime", XSD::QName.new(NsV1, "OrderBumpTimes")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => ArrayOfOrderBumpTime,
    :schema_type => XSD::QName.new(NsV1, "ArrayOfOrderBumpTime"),
    :schema_element => [
      ["orderBumpTime", ["OrderBumpTime[]", XSD::QName.new(NsV1, "OrderBumpTime")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => OrderBumpTime,
    :schema_type => XSD::QName.new(NsV1, "OrderBumpTime"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["firstSendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "FirstSendTime")], [0, 1]],
      ["kitchenQueueId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "KitchenQueueId")], [0, 1]],
      ["orderId", ["SOAP::SOAPLong", XSD::QName.new(NsV1, "OrderId")], [0, 1]],
      ["sendNumber", ["SOAP::SOAPShort", XSD::QName.new(NsV1, "SendNumber")], [0, 1]],
      ["sendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "SendTime")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderItemBumpTimesRequest,
    :schema_type => XSD::QName.new(NsV1, "GetOrderItemBumpTimesRequest"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["businessDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV1, "BusinessDate")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderItemBumpTimesReply,
    :schema_type => XSD::QName.new(NsV1, "GetOrderItemBumpTimesReply"),
    :schema_basetype => XSD::QName.new(NsPosWebService, "Reply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]],
      ["orderItemBumpTimes", ["ArrayOfOrderItemBumpTime", XSD::QName.new(NsV1, "OrderItemBumpTimes")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => ArrayOfOrderItemBumpTime,
    :schema_type => XSD::QName.new(NsV1, "ArrayOfOrderItemBumpTime"),
    :schema_element => [
      ["orderItemBumpTime", ["OrderItemBumpTime[]", XSD::QName.new(NsV1, "OrderItemBumpTime")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => OrderItemBumpTime,
    :schema_type => XSD::QName.new(NsV1, "OrderItemBumpTime"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["fireTime", ["DateTimeOffset", XSD::QName.new(NsV1, "FireTime")], [0, 1]],
      ["kitchenQueueId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "KitchenQueueId")], [0, 1]],
      ["orderId", ["SOAP::SOAPLong", XSD::QName.new(NsV1, "OrderId")], [0, 1]],
      ["orderItemId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "OrderItemId")], [0, 1]],
      ["sendNumber", ["SOAP::SOAPShort", XSD::QName.new(NsV1, "SendNumber")], [0, 1]],
      ["sendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "SendTime")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => DateTimeOffset,
    :schema_type => XSD::QName.new(NsSystem, "DateTimeOffset"),
    :schema_element => [
      ["dateTime", ["SOAP::SOAPDateTime", XSD::QName.new(NsSystem, "DateTime")]],
      ["offsetMinutes", ["SOAP::SOAPShort", XSD::QName.new(NsSystem, "OffsetMinutes")]]
    ]
  )

  LiteralRegistry.register(
    :class => Reply,
    :schema_type => XSD::QName.new(NsPosWebService, "Reply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderBumpTimes,
    :schema_name => XSD::QName.new(NsV1, "GetOrderBumpTimes"),
    :schema_element => [
      ["request", "GetOrderBumpTimesRequest", [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderBumpTimesRequest,
    :schema_name => XSD::QName.new(NsV1, "GetOrderBumpTimesRequest"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["businessDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV1, "BusinessDate")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderBumpTimesResponse,
    :schema_name => XSD::QName.new(NsV1, "GetOrderBumpTimesResponse"),
    :schema_element => [
      ["getOrderBumpTimesResult", ["GetOrderBumpTimesReply", XSD::QName.new(NsV1, "GetOrderBumpTimesResult")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderBumpTimesReply,
    :schema_name => XSD::QName.new(NsV1, "GetOrderBumpTimesReply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]],
      ["orderBumpTimes", ["ArrayOfOrderBumpTime", XSD::QName.new(NsV1, "OrderBumpTimes")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => ArrayOfOrderBumpTime,
    :schema_name => XSD::QName.new(NsV1, "ArrayOfOrderBumpTime"),
    :schema_element => [
      ["orderBumpTime", ["OrderBumpTime[]", XSD::QName.new(NsV1, "OrderBumpTime")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => OrderBumpTime,
    :schema_name => XSD::QName.new(NsV1, "OrderBumpTime"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["firstSendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "FirstSendTime")], [0, 1]],
      ["kitchenQueueId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "KitchenQueueId")], [0, 1]],
      ["orderId", ["SOAP::SOAPLong", XSD::QName.new(NsV1, "OrderId")], [0, 1]],
      ["sendNumber", ["SOAP::SOAPShort", XSD::QName.new(NsV1, "SendNumber")], [0, 1]],
      ["sendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "SendTime")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderItemBumpTimes,
    :schema_name => XSD::QName.new(NsV1, "GetOrderItemBumpTimes"),
    :schema_element => [
      ["request", "GetOrderItemBumpTimesRequest", [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderItemBumpTimesRequest,
    :schema_name => XSD::QName.new(NsV1, "GetOrderItemBumpTimesRequest"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["businessDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV1, "BusinessDate")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderItemBumpTimesResponse,
    :schema_name => XSD::QName.new(NsV1, "GetOrderItemBumpTimesResponse"),
    :schema_element => [
      ["getOrderItemBumpTimesResult", ["GetOrderItemBumpTimesReply", XSD::QName.new(NsV1, "GetOrderItemBumpTimesResult")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => GetOrderItemBumpTimesReply,
    :schema_name => XSD::QName.new(NsV1, "GetOrderItemBumpTimesReply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]],
      ["orderItemBumpTimes", ["ArrayOfOrderItemBumpTime", XSD::QName.new(NsV1, "OrderItemBumpTimes")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => ArrayOfOrderItemBumpTime,
    :schema_name => XSD::QName.new(NsV1, "ArrayOfOrderItemBumpTime"),
    :schema_element => [
      ["orderItemBumpTime", ["OrderItemBumpTime[]", XSD::QName.new(NsV1, "OrderItemBumpTime")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => OrderItemBumpTime,
    :schema_name => XSD::QName.new(NsV1, "OrderItemBumpTime"),
    :schema_element => [
      ["bumpTime", ["DateTimeOffset", XSD::QName.new(NsV1, "BumpTime")], [0, 1]],
      ["fireTime", ["DateTimeOffset", XSD::QName.new(NsV1, "FireTime")], [0, 1]],
      ["kitchenQueueId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "KitchenQueueId")], [0, 1]],
      ["orderId", ["SOAP::SOAPLong", XSD::QName.new(NsV1, "OrderId")], [0, 1]],
      ["orderItemId", ["SOAP::SOAPInt", XSD::QName.new(NsV1, "OrderItemId")], [0, 1]],
      ["sendNumber", ["SOAP::SOAPShort", XSD::QName.new(NsV1, "SendNumber")], [0, 1]],
      ["sendTime", ["DateTimeOffset", XSD::QName.new(NsV1, "SendTime")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => DateTimeOffset,
    :schema_name => XSD::QName.new(NsSystem, "DateTimeOffset"),
    :schema_element => [
      ["dateTime", ["SOAP::SOAPDateTime", XSD::QName.new(NsSystem, "DateTime")]],
      ["offsetMinutes", ["SOAP::SOAPShort", XSD::QName.new(NsSystem, "OffsetMinutes")]]
    ]
  )

  LiteralRegistry.register(
    :class => Reply,
    :schema_name => XSD::QName.new(NsPosWebService, "Reply"),
    :schema_element => [
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsPosWebService, "Message")], [0, 1]],
      ["resultCode", ["SOAP::SOAPInt", XSD::QName.new(NsPosWebService, "ResultCode")], [0, 1]]
    ]
  )
end
