# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require 'xsd/qname'

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderBumpTimesRequest
#   bumpTime - DateTimeOffset
#   businessDate - SOAP::SOAPDateTime
class GetOrderBumpTimesRequest
  attr_accessor :bumpTime
  attr_accessor :businessDate

  def initialize(bumpTime = nil, businessDate = nil)
    @bumpTime = bumpTime
    @businessDate = businessDate
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}ArrayOfOrderBumpTime
class ArrayOfOrderBumpTime < ::Array
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}OrderBumpTime
#   bumpTime - DateTimeOffset
#   firstSendTime - DateTimeOffset
#   kitchenQueueId - SOAP::SOAPInt
#   orderId - SOAP::SOAPLong
#   sendNumber - SOAP::SOAPShort
#   sendTime - DateTimeOffset
class OrderBumpTime
  attr_accessor :bumpTime
  attr_accessor :firstSendTime
  attr_accessor :kitchenQueueId
  attr_accessor :orderId
  attr_accessor :sendNumber
  attr_accessor :sendTime

  def initialize(bumpTime = nil, firstSendTime = nil, kitchenQueueId = nil, orderId = nil, sendNumber = nil, sendTime = nil)
    @bumpTime = bumpTime
    @firstSendTime = firstSendTime
    @kitchenQueueId = kitchenQueueId
    @orderId = orderId
    @sendNumber = sendNumber
    @sendTime = sendTime
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderItemBumpTimesRequest
#   bumpTime - DateTimeOffset
#   businessDate - SOAP::SOAPDateTime
class GetOrderItemBumpTimesRequest
  attr_accessor :bumpTime
  attr_accessor :businessDate

  def initialize(bumpTime = nil, businessDate = nil)
    @bumpTime = bumpTime
    @businessDate = businessDate
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}ArrayOfOrderItemBumpTime
class ArrayOfOrderItemBumpTime < ::Array
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}OrderItemBumpTime
#   bumpTime - DateTimeOffset
#   fireTime - DateTimeOffset
#   kitchenQueueId - SOAP::SOAPInt
#   orderId - SOAP::SOAPLong
#   orderItemId - SOAP::SOAPInt
#   sendNumber - SOAP::SOAPShort
#   sendTime - DateTimeOffset
class OrderItemBumpTime
  attr_accessor :bumpTime
  attr_accessor :fireTime
  attr_accessor :kitchenQueueId
  attr_accessor :orderId
  attr_accessor :orderItemId
  attr_accessor :sendNumber
  attr_accessor :sendTime

  def initialize(bumpTime = nil, fireTime = nil, kitchenQueueId = nil, orderId = nil, orderItemId = nil, sendNumber = nil, sendTime = nil)
    @bumpTime = bumpTime
    @fireTime = fireTime
    @kitchenQueueId = kitchenQueueId
    @orderId = orderId
    @orderItemId = orderItemId
    @sendNumber = sendNumber
    @sendTime = sendTime
  end
end

# {http://schemas.datacontract.org/2004/07/System}DateTimeOffset
#   dateTime - SOAP::SOAPDateTime
#   offsetMinutes - SOAP::SOAPShort
class DateTimeOffset
  attr_accessor :dateTime
  attr_accessor :offsetMinutes

  def initialize(dateTime = nil, offsetMinutes = nil)
    @dateTime = dateTime
    @offsetMinutes = offsetMinutes
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service}Reply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class Reply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderBumpTimesReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   orderBumpTimes - ArrayOfOrderBumpTime
class GetOrderBumpTimesReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :orderBumpTimes

  def initialize(message = nil, resultCode = nil, orderBumpTimes = nil)
    @message = message
    @resultCode = resultCode
    @orderBumpTimes = orderBumpTimes
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderItemBumpTimesReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   orderItemBumpTimes - ArrayOfOrderItemBumpTime
class GetOrderItemBumpTimesReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :orderItemBumpTimes

  def initialize(message = nil, resultCode = nil, orderItemBumpTimes = nil)
    @message = message
    @resultCode = resultCode
    @orderItemBumpTimes = orderItemBumpTimes
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderBumpTimes
#   request - GetOrderBumpTimesRequest
class GetOrderBumpTimes
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderBumpTimesResponse
#   getOrderBumpTimesResult - GetOrderBumpTimesReply
class GetOrderBumpTimesResponse
  attr_accessor :getOrderBumpTimesResult

  def initialize(getOrderBumpTimesResult = nil)
    @getOrderBumpTimesResult = getOrderBumpTimesResult
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderItemBumpTimes
#   request - GetOrderItemBumpTimesRequest
class GetOrderItemBumpTimes
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/kitchen/v1}GetOrderItemBumpTimesResponse
#   getOrderItemBumpTimesResult - GetOrderItemBumpTimesReply
class GetOrderItemBumpTimesResponse
  attr_accessor :getOrderItemBumpTimesResult

  def initialize(getOrderItemBumpTimesResult = nil)
    @getOrderItemBumpTimesResult = getOrderItemBumpTimesResult
  end
end
