# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'KitchenWebService.rb'
require_relative 'KitchenWebServiceMappingRegistry.rb'
require 'soap/rpc/driver'

class IKitchenWebService < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "http://api-devapi01.brinkpos.net/Kitchen.svc"

  Methods = [
    [ "http://www.brinksoftware.com/webservices/kitchen/v1/IKitchenWebService/GetOrderBumpTimes",
      "getOrderBumpTimes",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/kitchen/v1", "GetOrderBumpTimes"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/kitchen/v1", "GetOrderBumpTimesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.brinksoftware.com/webservices/kitchen/v1/IKitchenWebService/GetOrderItemBumpTimes",
      "getOrderItemBumpTimes",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/kitchen/v1", "GetOrderItemBumpTimes"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/kitchen/v1", "GetOrderItemBumpTimesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = KitchenWebServiceMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = KitchenWebServiceMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

