#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'LaborWebService2Driver.rb'

endpoint_url = ARGV.shift
obj = ILaborWebService2.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   getLaborSchedule(parameters)
#
# ARGS
#   parameters      GetLaborSchedule - {http://www.brinksoftware.com/webservices/labor/v2}GetLaborSchedule
#
# RETURNS
#   parameters      GetLaborScheduleResponse - {http://www.brinksoftware.com/webservices/labor/v2}GetLaborScheduleResponse
#
parameters = nil
puts obj.getLaborSchedule(parameters)

# SYNOPSIS
#   getShifts(parameters)
#
# ARGS
#   parameters      GetShifts - {http://www.brinksoftware.com/webservices/labor/v2}GetShifts
#
# RETURNS
#   parameters      GetShiftsResponse - {http://www.brinksoftware.com/webservices/labor/v2}GetShiftsResponse
#
parameters = nil
puts obj.getShifts(parameters)

# SYNOPSIS
#   saveLaborSchedule(parameters)
#
# ARGS
#   parameters      SaveLaborSchedule - {http://www.brinksoftware.com/webservices/labor/v2}SaveLaborSchedule
#
# RETURNS
#   parameters      SaveLaborScheduleResponse - {http://www.brinksoftware.com/webservices/labor/v2}SaveLaborScheduleResponse
#
parameters = nil
puts obj.saveLaborSchedule(parameters)


