#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'LoyaltyWebService2Driver.rb'

endpoint_url = ARGV.shift
obj = ILoyaltyWebService2.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   addManualAdjustment(parameters)
#
# ARGS
#   parameters      AddManualAdjustment - {http://www.brinksoftware.com/webservices/loyalty/v2}AddManualAdjustment
#
# RETURNS
#   parameters      AddManualAdjustmentResponse - {http://www.brinksoftware.com/webservices/loyalty/v2}AddManualAdjustmentResponse
#
parameters = nil
puts obj.addManualAdjustment(parameters)

# SYNOPSIS
#   getActivity(parameters)
#
# ARGS
#   parameters      GetActivity - {http://www.brinksoftware.com/webservices/loyalty/v2}GetActivity
#
# RETURNS
#   parameters      GetActivityResponse - {http://www.brinksoftware.com/webservices/loyalty/v2}GetActivityResponse
#
parameters = nil
puts obj.getActivity(parameters)

# SYNOPSIS
#   getAdjustmentDetails(parameters)
#
# ARGS
#   parameters      GetAdjustmentDetails - {http://www.brinksoftware.com/webservices/loyalty/v2}GetAdjustmentDetails
#
# RETURNS
#   parameters      GetAdjustmentDetailsResponse - {http://www.brinksoftware.com/webservices/loyalty/v2}GetAdjustmentDetailsResponse
#
parameters = nil
puts obj.getAdjustmentDetails(parameters)

# SYNOPSIS
#   getAwardRedemptions(parameters)
#
# ARGS
#   parameters      GetAwardRedemptions - {http://www.brinksoftware.com/webservices/loyalty/v2}GetAwardRedemptions
#
# RETURNS
#   parameters      GetAwardRedemptionsResponse - {http://www.brinksoftware.com/webservices/loyalty/v2}GetAwardRedemptionsResponse
#
parameters = nil
puts obj.getAwardRedemptions(parameters)

# SYNOPSIS
#   redeemAwards(parameters)
#
# ARGS
#   parameters      RedeemAwards - {http://www.brinksoftware.com/webservices/loyalty/v2}RedeemAwards
#
# RETURNS
#   parameters      RedeemAwardsResponse - {http://www.brinksoftware.com/webservices/loyalty/v2}RedeemAwardsResponse
#
parameters = nil
puts obj.redeemAwards(parameters)


