# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require 'xsd/qname'

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetActivityRequest
#   customerId - (any)
#   groupToken - SOAP::SOAPString
#   recordOffset - SOAP::SOAPUnsignedInt
#   startTime - DateTimeOffset
class GetActivityRequest
  attr_accessor :customerId
  attr_accessor :groupToken
  attr_accessor :recordOffset
  attr_accessor :startTime

  def initialize(customerId = nil, groupToken = nil, recordOffset = nil, startTime = nil)
    @customerId = customerId
    @groupToken = groupToken
    @recordOffset = recordOffset
    @startTime = startTime
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}ArrayOfActivityDetail
class ArrayOfActivityDetail < ::Array
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}ActivityDetail
#   customerId - (any)
#   locationId - (any)
#   orderId - SOAP::SOAPLong
#   planId - SOAP::SOAPInt
#   time - DateTimeOffset
#   type - SOAP::SOAPUnsignedByte
#   value - SOAP::SOAPDecimal
class ActivityDetail
  attr_accessor :customerId
  attr_accessor :locationId
  attr_accessor :orderId
  attr_accessor :planId
  attr_accessor :time
  attr_accessor :type
  attr_accessor :value

  def initialize(customerId = nil, locationId = nil, orderId = nil, planId = nil, time = nil, type = nil, value = nil)
    @customerId = customerId
    @locationId = locationId
    @orderId = orderId
    @planId = planId
    @time = time
    @type = type
    @value = value
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAdjustmentDetailsRequest
#   groupToken - SOAP::SOAPString
#   includeBulkAdjustments - SOAP::SOAPBoolean
#   recordOffset - SOAP::SOAPUnsignedInt
#   startTime - DateTimeOffset
class GetAdjustmentDetailsRequest
  attr_accessor :groupToken
  attr_accessor :includeBulkAdjustments
  attr_accessor :recordOffset
  attr_accessor :startTime

  def initialize(groupToken = nil, includeBulkAdjustments = nil, recordOffset = nil, startTime = nil)
    @groupToken = groupToken
    @includeBulkAdjustments = includeBulkAdjustments
    @recordOffset = recordOffset
    @startTime = startTime
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}ArrayOfAdjustmentDetail
class ArrayOfAdjustmentDetail < ::Array
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}AdjustmentDetail
#   activityType - SOAP::SOAPInt
#   customerId - (any)
#   isBulkAdjustment - SOAP::SOAPBoolean
#   notes - SOAP::SOAPString
#   planId - SOAP::SOAPInt
#   reasonId - SOAP::SOAPInt
#   rewardId - SOAP::SOAPInt
#   rewardValue - SOAP::SOAPDecimal
#   time - DateTimeOffset
#   value - SOAP::SOAPDecimal
class AdjustmentDetail
  attr_accessor :activityType
  attr_accessor :customerId
  attr_accessor :isBulkAdjustment
  attr_accessor :notes
  attr_accessor :planId
  attr_accessor :reasonId
  attr_accessor :rewardId
  attr_accessor :rewardValue
  attr_accessor :time
  attr_accessor :value

  def initialize(activityType = nil, customerId = nil, isBulkAdjustment = nil, notes = nil, planId = nil, reasonId = nil, rewardId = nil, rewardValue = nil, time = nil, value = nil)
    @activityType = activityType
    @customerId = customerId
    @isBulkAdjustment = isBulkAdjustment
    @notes = notes
    @planId = planId
    @reasonId = reasonId
    @rewardId = rewardId
    @rewardValue = rewardValue
    @time = time
    @value = value
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAwardRedemptionsRequest
#   customerId - (any)
#   groupToken - SOAP::SOAPString
#   recordOffset - SOAP::SOAPUnsignedInt
#   startTime - DateTimeOffset
class GetAwardRedemptionsRequest
  attr_accessor :customerId
  attr_accessor :groupToken
  attr_accessor :recordOffset
  attr_accessor :startTime

  def initialize(customerId = nil, groupToken = nil, recordOffset = nil, startTime = nil)
    @customerId = customerId
    @groupToken = groupToken
    @recordOffset = recordOffset
    @startTime = startTime
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}ArrayOfAwardRedemption
class ArrayOfAwardRedemption < ::Array
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}AwardRedemption
#   awardId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   locationId - (any)
#   orderId - SOAP::SOAPLong
#   time - DateTimeOffset
#   value - SOAP::SOAPDecimal
class AwardRedemption
  attr_accessor :awardId
  attr_accessor :id
  attr_accessor :locationId
  attr_accessor :orderId
  attr_accessor :time
  attr_accessor :value

  def initialize(awardId = nil, id = nil, locationId = nil, orderId = nil, time = nil, value = nil)
    @awardId = awardId
    @id = id
    @locationId = locationId
    @orderId = orderId
    @time = time
    @value = value
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}RedeemAwardsRequest
#   allowPartialSuccess - SOAP::SOAPBoolean
#   awardIds - ArrayOfint
#   groupToken - SOAP::SOAPString
class RedeemAwardsRequest
  attr_accessor :allowPartialSuccess
  attr_accessor :awardIds
  attr_accessor :groupToken

  def initialize(allowPartialSuccess = nil, awardIds = nil, groupToken = nil)
    @allowPartialSuccess = allowPartialSuccess
    @awardIds = awardIds
    @groupToken = groupToken
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Loyalty.Version2.Operations}AddManualAdjustmentRequest
#   customerId - (any)
#   groupToken - SOAP::SOAPString
#   planId - SOAP::SOAPInt
#   reasonId - SOAP::SOAPInt
#   value - SOAP::SOAPDecimal
class AddManualAdjustmentRequest
  attr_accessor :customerId
  attr_accessor :groupToken
  attr_accessor :planId
  attr_accessor :reasonId
  attr_accessor :value

  def initialize(customerId = nil, groupToken = nil, planId = nil, reasonId = nil, value = nil)
    @customerId = customerId
    @groupToken = groupToken
    @planId = planId
    @reasonId = reasonId
    @value = value
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service}Reply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class Reply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}LoyaltyWebService2Reply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class LoyaltyWebService2Reply < Reply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}AddManualAdjustmentReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class AddManualAdjustmentReply < LoyaltyWebService2Reply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetActivityReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   activity - ArrayOfActivityDetail
class GetActivityReply < LoyaltyWebService2Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :activity

  def initialize(message = nil, resultCode = nil, activity = nil)
    @message = message
    @resultCode = resultCode
    @activity = activity
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAdjustmentDetailsReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   adjustments - ArrayOfAdjustmentDetail
class GetAdjustmentDetailsReply < LoyaltyWebService2Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :adjustments

  def initialize(message = nil, resultCode = nil, adjustments = nil)
    @message = message
    @resultCode = resultCode
    @adjustments = adjustments
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAwardRedemptionsReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   redemptions - ArrayOfAwardRedemption
class GetAwardRedemptionsReply < LoyaltyWebService2Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :redemptions

  def initialize(message = nil, resultCode = nil, redemptions = nil)
    @message = message
    @resultCode = resultCode
    @redemptions = redemptions
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}RedeemAwardsReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   alreadyRedeemedAwardIds - ArrayOfint
#   invalidAwardIds - ArrayOfint
#   successfulAwardIds - ArrayOfint
class RedeemAwardsReply < LoyaltyWebService2Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :alreadyRedeemedAwardIds
  attr_accessor :invalidAwardIds
  attr_accessor :successfulAwardIds

  def initialize(message = nil, resultCode = nil, alreadyRedeemedAwardIds = nil, invalidAwardIds = nil, successfulAwardIds = nil)
    @message = message
    @resultCode = resultCode
    @alreadyRedeemedAwardIds = alreadyRedeemedAwardIds
    @invalidAwardIds = invalidAwardIds
    @successfulAwardIds = successfulAwardIds
  end
end

# {http://schemas.datacontract.org/2004/07/System}DateTimeOffset
#   dateTime - SOAP::SOAPDateTime
#   offsetMinutes - SOAP::SOAPShort
class DateTimeOffset
  attr_accessor :dateTime
  attr_accessor :offsetMinutes

  def initialize(dateTime = nil, offsetMinutes = nil)
    @dateTime = dateTime
    @offsetMinutes = offsetMinutes
  end
end

# {http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfint
class ArrayOfint < ::Array
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}AddManualAdjustment
#   request - AddManualAdjustmentRequest
class AddManualAdjustment
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}AddManualAdjustmentResponse
#   addManualAdjustmentResult - AddManualAdjustmentReply
class AddManualAdjustmentResponse
  attr_accessor :addManualAdjustmentResult

  def initialize(addManualAdjustmentResult = nil)
    @addManualAdjustmentResult = addManualAdjustmentResult
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetActivity
#   request - GetActivityRequest
class GetActivity
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetActivityResponse
#   getActivityResult - GetActivityReply
class GetActivityResponse
  attr_accessor :getActivityResult

  def initialize(getActivityResult = nil)
    @getActivityResult = getActivityResult
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAdjustmentDetails
#   request - GetAdjustmentDetailsRequest
class GetAdjustmentDetails
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAdjustmentDetailsResponse
#   getAdjustmentDetailsResult - GetAdjustmentDetailsReply
class GetAdjustmentDetailsResponse
  attr_accessor :getAdjustmentDetailsResult

  def initialize(getAdjustmentDetailsResult = nil)
    @getAdjustmentDetailsResult = getAdjustmentDetailsResult
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAwardRedemptions
#   request - GetAwardRedemptionsRequest
class GetAwardRedemptions
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}GetAwardRedemptionsResponse
#   getAwardRedemptionsResult - GetAwardRedemptionsReply
class GetAwardRedemptionsResponse
  attr_accessor :getAwardRedemptionsResult

  def initialize(getAwardRedemptionsResult = nil)
    @getAwardRedemptionsResult = getAwardRedemptionsResult
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}RedeemAwards
#   request - RedeemAwardsRequest
class RedeemAwards
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/loyalty/v2}RedeemAwardsResponse
#   redeemAwardsResult - RedeemAwardsReply
class RedeemAwardsResponse
  attr_accessor :redeemAwardsResult

  def initialize(redeemAwardsResult = nil)
    @redeemAwardsResult = redeemAwardsResult
  end
end
