# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'LoyaltyWebService2.rb'
require_relative 'LoyaltyWebService2MappingRegistry.rb'
require 'soap/rpc/driver'

class ILoyaltyWebService2 < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "http://api-devapi01.brinkpos.net/Loyalty2.svc"

  Methods = [
    [ "http://www.brinksoftware.com/webservices/loyalty/v2/ILoyaltyWebService2/AddManualAdjustment",
      "addManualAdjustment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "AddManualAdjustment"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "AddManualAdjustmentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.brinksoftware.com/webservices/loyalty/v2/ILoyaltyWebService2/GetActivity",
      "getActivity",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "GetActivity"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "GetActivityResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.brinksoftware.com/webservices/loyalty/v2/ILoyaltyWebService2/GetAdjustmentDetails",
      "getAdjustmentDetails",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "GetAdjustmentDetails"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "GetAdjustmentDetailsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.brinksoftware.com/webservices/loyalty/v2/ILoyaltyWebService2/GetAwardRedemptions",
      "getAwardRedemptions",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "GetAwardRedemptions"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "GetAwardRedemptionsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://www.brinksoftware.com/webservices/loyalty/v2/ILoyaltyWebService2/RedeemAwards",
      "redeemAwards",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "RedeemAwards"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "http://www.brinksoftware.com/webservices/loyalty/v2", "RedeemAwardsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = LoyaltyWebService2MappingRegistry::EncodedRegistry
    self.literal_mapping_registry = LoyaltyWebService2MappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

