# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require 'xsd/qname'

# {http://www.brinksoftware.com/webservices/ordering/20140219}CalculateOrderRequest
#   options - OrderingOptions
#   order - NewOrder
class CalculateOrderRequest
  attr_accessor :options
  attr_accessor :order

  def initialize(options = nil, order = nil)
    @options = options
    @order = order
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderingOptions
#   calculateItemPrice - SOAP::SOAPBoolean
class OrderingOptions
  attr_accessor :calculateItemPrice

  def initialize(calculateItemPrice = nil)
    @calculateItemPrice = calculateItemPrice
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrder
#   customerId - (any)
#   destinationId - SOAP::SOAPInt
#   discounts - ArrayOfNewOrderDiscount
#   futureOrder - NewFutureOrderDetails
#   isTaxExempt - SOAP::SOAPBoolean
#   items - ArrayOfNewOrderItem
#   name - SOAP::SOAPString
#   payments - ArrayOfNewOrderPayment
#   promotions - ArrayOfNewOrderPromotion
#   sectionId - SOAP::SOAPInt
#   surcharges - ArrayOfNewOrderSurcharge
class NewOrder
  attr_accessor :customerId
  attr_accessor :destinationId
  attr_accessor :discounts
  attr_accessor :futureOrder
  attr_accessor :isTaxExempt
  attr_accessor :items
  attr_accessor :name
  attr_accessor :payments
  attr_accessor :promotions
  attr_accessor :sectionId
  attr_accessor :surcharges

  def initialize(customerId = nil, destinationId = nil, discounts = nil, futureOrder = nil, isTaxExempt = nil, items = nil, name = nil, payments = nil, promotions = nil, sectionId = nil, surcharges = nil)
    @customerId = customerId
    @destinationId = destinationId
    @discounts = discounts
    @futureOrder = futureOrder
    @isTaxExempt = isTaxExempt
    @items = items
    @name = name
    @payments = payments
    @promotions = promotions
    @sectionId = sectionId
    @surcharges = surcharges
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfNewOrderDiscount
class ArrayOfNewOrderDiscount < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrderDiscount
#   amount - SOAP::SOAPDecimal
#   discountId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   loyaltyRewardId - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   orderItemIds - ArrayOfint
#   percent - SOAP::SOAPDecimal
class NewOrderDiscount
  attr_accessor :amount
  attr_accessor :discountId
  attr_accessor :id
  attr_accessor :loyaltyRewardId
  attr_accessor :name
  attr_accessor :orderItemIds
  attr_accessor :percent

  def initialize(amount = nil, discountId = nil, id = nil, loyaltyRewardId = nil, name = nil, orderItemIds = nil, percent = nil)
    @amount = amount
    @discountId = discountId
    @id = id
    @loyaltyRewardId = loyaltyRewardId
    @name = name
    @orderItemIds = orderItemIds
    @percent = percent
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewFutureOrderDetails
#   delivery - NewDeliveryDetails
#   emailAddress - SOAP::SOAPString
#   phoneNumber - SOAP::SOAPString
#   pickupTime - DateTimeOffset
#   sendReminderEmail - SOAP::SOAPBoolean
class NewFutureOrderDetails
  attr_accessor :delivery
  attr_accessor :emailAddress
  attr_accessor :phoneNumber
  attr_accessor :pickupTime
  attr_accessor :sendReminderEmail

  def initialize(delivery = nil, emailAddress = nil, phoneNumber = nil, pickupTime = nil, sendReminderEmail = nil)
    @delivery = delivery
    @emailAddress = emailAddress
    @phoneNumber = phoneNumber
    @pickupTime = pickupTime
    @sendReminderEmail = sendReminderEmail
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewDeliveryDetails
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   city - SOAP::SOAPString
#   country - SOAP::SOAPString
#   postalCode - SOAP::SOAPString
#   stateCode - SOAP::SOAPString
class NewDeliveryDetails
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :city
  attr_accessor :country
  attr_accessor :postalCode
  attr_accessor :stateCode

  def initialize(address1 = nil, address2 = nil, city = nil, country = nil, postalCode = nil, stateCode = nil)
    @address1 = address1
    @address2 = address2
    @city = city
    @country = country
    @postalCode = postalCode
    @stateCode = stateCode
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfNewOrderItem
class ArrayOfNewOrderItem < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrderItemBase
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   menuItemId - SOAP::SOAPInt
#   modifiers - ArrayOfNewOrderItemModifier
#   price - SOAP::SOAPDecimal
class NewOrderItemBase
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :menuItemId
  attr_accessor :modifiers
  attr_accessor :price

  def initialize(description = nil, id = nil, itemId = nil, menuItemId = nil, modifiers = nil, price = nil)
    @description = description
    @id = id
    @itemId = itemId
    @menuItemId = menuItemId
    @modifiers = modifiers
    @price = price
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrderItem
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   menuItemId - SOAP::SOAPInt
#   modifiers - ArrayOfNewOrderItemModifier
#   price - SOAP::SOAPDecimal
#   comboItems - ArrayOfNewOrderItem
#   componentId - SOAP::SOAPInt
#   destinationId - SOAP::SOAPInt
#   note - SOAP::SOAPString
#   seat - SOAP::SOAPUnsignedByte
class NewOrderItem < NewOrderItemBase
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :menuItemId
  attr_accessor :modifiers
  attr_accessor :price
  attr_accessor :comboItems
  attr_accessor :componentId
  attr_accessor :destinationId
  attr_accessor :note
  attr_accessor :seat

  def initialize(description = nil, id = nil, itemId = nil, menuItemId = nil, modifiers = nil, price = nil, comboItems = nil, componentId = nil, destinationId = nil, note = nil, seat = nil)
    @description = description
    @id = id
    @itemId = itemId
    @menuItemId = menuItemId
    @modifiers = modifiers
    @price = price
    @comboItems = comboItems
    @componentId = componentId
    @destinationId = destinationId
    @note = note
    @seat = seat
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrderItemModifier
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   menuItemId - SOAP::SOAPInt
#   modifiers - ArrayOfNewOrderItemModifier
#   price - SOAP::SOAPDecimal
#   modifierCodeId - SOAP::SOAPInt
#   modifierGroupId - SOAP::SOAPInt
class NewOrderItemModifier < NewOrderItemBase
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :menuItemId
  attr_accessor :modifiers
  attr_accessor :price
  attr_accessor :modifierCodeId
  attr_accessor :modifierGroupId

  def initialize(description = nil, id = nil, itemId = nil, menuItemId = nil, modifiers = nil, price = nil, modifierCodeId = nil, modifierGroupId = nil)
    @description = description
    @id = id
    @itemId = itemId
    @menuItemId = menuItemId
    @modifiers = modifiers
    @price = price
    @modifierCodeId = modifierCodeId
    @modifierGroupId = modifierGroupId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfNewOrderItemModifier
class ArrayOfNewOrderItemModifier < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfNewOrderPayment
class ArrayOfNewOrderPayment < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrderPayment
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
class NewOrderPayment
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :tenderId
  attr_accessor :tipAmount

  def initialize(amount = nil, id = nil, tenderId = nil, tipAmount = nil)
    @amount = amount
    @id = id
    @tenderId = tenderId
    @tipAmount = tipAmount
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewCheckPayment
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
#   checkNumber - SOAP::SOAPString
class NewCheckPayment < NewOrderPayment
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :tenderId
  attr_accessor :tipAmount
  attr_accessor :checkNumber

  def initialize(amount = nil, id = nil, tenderId = nil, tipAmount = nil, checkNumber = nil)
    @amount = amount
    @id = id
    @tenderId = tenderId
    @tipAmount = tipAmount
    @checkNumber = checkNumber
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewCreditCardPayment
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
#   accountNumber - SOAP::SOAPString
#   city - SOAP::SOAPString
#   country - SOAP::SOAPString
#   cvv - SOAP::SOAPString
#   expirationDate - SOAP::SOAPString
#   nameOnCard - SOAP::SOAPString
#   postalCode - SOAP::SOAPString
#   state - SOAP::SOAPString
#   streetAddress - SOAP::SOAPString
class NewCreditCardPayment < NewOrderPayment
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :tenderId
  attr_accessor :tipAmount
  attr_accessor :accountNumber
  attr_accessor :city
  attr_accessor :country
  attr_accessor :cvv
  attr_accessor :expirationDate
  attr_accessor :nameOnCard
  attr_accessor :postalCode
  attr_accessor :state
  attr_accessor :streetAddress

  def initialize(amount = nil, id = nil, tenderId = nil, tipAmount = nil, accountNumber = nil, city = nil, country = nil, cvv = nil, expirationDate = nil, nameOnCard = nil, postalCode = nil, state = nil, streetAddress = nil)
    @amount = amount
    @id = id
    @tenderId = tenderId
    @tipAmount = tipAmount
    @accountNumber = accountNumber
    @city = city
    @country = country
    @cvv = cvv
    @expirationDate = expirationDate
    @nameOnCard = nameOnCard
    @postalCode = postalCode
    @state = state
    @streetAddress = streetAddress
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewExternalPayment
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
#   referenceDetails - ArrayOfPaymentReferenceDetail
class NewExternalPayment < NewOrderPayment
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :tenderId
  attr_accessor :tipAmount
  attr_accessor :referenceDetails

  def initialize(amount = nil, id = nil, tenderId = nil, tipAmount = nil, referenceDetails = nil)
    @amount = amount
    @id = id
    @tenderId = tenderId
    @tipAmount = tipAmount
    @referenceDetails = referenceDetails
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewGiftCardPayment
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
#   accountNumber - SOAP::SOAPString
#   cvv - SOAP::SOAPString
#   expirationDate - SOAP::SOAPString
class NewGiftCardPayment < NewOrderPayment
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :tenderId
  attr_accessor :tipAmount
  attr_accessor :accountNumber
  attr_accessor :cvv
  attr_accessor :expirationDate

  def initialize(amount = nil, id = nil, tenderId = nil, tipAmount = nil, accountNumber = nil, cvv = nil, expirationDate = nil)
    @amount = amount
    @id = id
    @tenderId = tenderId
    @tipAmount = tipAmount
    @accountNumber = accountNumber
    @cvv = cvv
    @expirationDate = expirationDate
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewGiftCertificatePayment
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
class NewGiftCertificatePayment < NewOrderPayment
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :tenderId
  attr_accessor :tipAmount

  def initialize(amount = nil, id = nil, tenderId = nil, tipAmount = nil)
    @amount = amount
    @id = id
    @tenderId = tenderId
    @tipAmount = tipAmount
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfPaymentReferenceDetail
class ArrayOfPaymentReferenceDetail < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}PaymentReferenceDetail
#   name - SOAP::SOAPString
#   value - SOAP::SOAPString
class PaymentReferenceDetail
  attr_accessor :name
  attr_accessor :value

  def initialize(name = nil, value = nil)
    @name = name
    @value = value
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfNewOrderPromotion
class ArrayOfNewOrderPromotion < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrderPromotion
#   amount - SOAP::SOAPDecimal
#   code - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   promotionId - SOAP::SOAPInt
#   requiredOrderItemIds - ArrayOfint
#   targetOrderItemIds - ArrayOfint
class NewOrderPromotion
  attr_accessor :amount
  attr_accessor :code
  attr_accessor :id
  attr_accessor :name
  attr_accessor :promotionId
  attr_accessor :requiredOrderItemIds
  attr_accessor :targetOrderItemIds

  def initialize(amount = nil, code = nil, id = nil, name = nil, promotionId = nil, requiredOrderItemIds = nil, targetOrderItemIds = nil)
    @amount = amount
    @code = code
    @id = id
    @name = name
    @promotionId = promotionId
    @requiredOrderItemIds = requiredOrderItemIds
    @targetOrderItemIds = targetOrderItemIds
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfNewOrderSurcharge
class ArrayOfNewOrderSurcharge < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}NewOrderSurcharge
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   surchargeId - SOAP::SOAPInt
class NewOrderSurcharge
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :name
  attr_accessor :surchargeId

  def initialize(amount = nil, id = nil, name = nil, surchargeId = nil)
    @amount = amount
    @id = id
    @name = name
    @surchargeId = surchargeId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}Order
#   balance - SOAP::SOAPDecimal
#   businessDate - SOAP::SOAPDateTime
#   createdTime - DateTimeOffset
#   customerId - (any)
#   destinationId - SOAP::SOAPInt
#   discounts - ArrayOfOrderDiscount
#   entries - ArrayOfOrderEntry
#   futureOrder - FutureOrderDetails
#   id - SOAP::SOAPLong
#   idEncoded - SOAP::SOAPString
#   isClosed - SOAP::SOAPBoolean
#   isSent - SOAP::SOAPBoolean
#   isTaxExempt - SOAP::SOAPBoolean
#   laneId - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   number - SOAP::SOAPInt
#   payments - ArrayOfOrderPayment
#   promotions - ArrayOfOrderPromotion
#   rounding - SOAP::SOAPDecimal
#   sectionId - SOAP::SOAPInt
#   subtotal - SOAP::SOAPDecimal
#   surcharges - ArrayOfOrderSurcharge
#   tax - SOAP::SOAPDecimal
#   total - SOAP::SOAPDecimal
class Order
  attr_accessor :balance
  attr_accessor :businessDate
  attr_accessor :createdTime
  attr_accessor :customerId
  attr_accessor :destinationId
  attr_accessor :discounts
  attr_accessor :entries
  attr_accessor :futureOrder
  attr_accessor :id
  attr_accessor :idEncoded
  attr_accessor :isClosed
  attr_accessor :isSent
  attr_accessor :isTaxExempt
  attr_accessor :laneId
  attr_accessor :name
  attr_accessor :number
  attr_accessor :payments
  attr_accessor :promotions
  attr_accessor :rounding
  attr_accessor :sectionId
  attr_accessor :subtotal
  attr_accessor :surcharges
  attr_accessor :tax
  attr_accessor :total

  def initialize(balance = nil, businessDate = nil, createdTime = nil, customerId = nil, destinationId = nil, discounts = nil, entries = nil, futureOrder = nil, id = nil, idEncoded = nil, isClosed = nil, isSent = nil, isTaxExempt = nil, laneId = nil, name = nil, number = nil, payments = nil, promotions = nil, rounding = nil, sectionId = nil, subtotal = nil, surcharges = nil, tax = nil, total = nil)
    @balance = balance
    @businessDate = businessDate
    @createdTime = createdTime
    @customerId = customerId
    @destinationId = destinationId
    @discounts = discounts
    @entries = entries
    @futureOrder = futureOrder
    @id = id
    @idEncoded = idEncoded
    @isClosed = isClosed
    @isSent = isSent
    @isTaxExempt = isTaxExempt
    @laneId = laneId
    @name = name
    @number = number
    @payments = payments
    @promotions = promotions
    @rounding = rounding
    @sectionId = sectionId
    @subtotal = subtotal
    @surcharges = surcharges
    @tax = tax
    @total = total
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderDiscount
class ArrayOfOrderDiscount < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderDiscount
#   amount - SOAP::SOAPDecimal
#   discountId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   loyaltyRewardId - SOAP::SOAPInt
#   name - SOAP::SOAPString
class OrderDiscount
  attr_accessor :amount
  attr_accessor :discountId
  attr_accessor :id
  attr_accessor :loyaltyRewardId
  attr_accessor :name

  def initialize(amount = nil, discountId = nil, id = nil, loyaltyRewardId = nil, name = nil)
    @amount = amount
    @discountId = discountId
    @id = id
    @loyaltyRewardId = loyaltyRewardId
    @name = name
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderEntry
class ArrayOfOrderEntry < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderEntry
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   price - SOAP::SOAPDecimal
#   promotions - ArrayOfOrderEntryPromotion
class OrderEntry
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :price
  attr_accessor :promotions

  def initialize(description = nil, id = nil, itemId = nil, price = nil, promotions = nil)
    @description = description
    @id = id
    @itemId = itemId
    @price = price
    @promotions = promotions
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderItem
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   price - SOAP::SOAPDecimal
#   promotions - ArrayOfOrderEntryPromotion
#   comboItems - ArrayOfOrderItem
#   componentId - SOAP::SOAPInt
#   compositeOrderItemId - SOAP::SOAPInt
#   denominator - SOAP::SOAPUnsignedByte
#   destinationId - SOAP::SOAPInt
#   discounts - ArrayOfOrderItemDiscount
#   modifiers - ArrayOfOrderItemModifier
#   note - SOAP::SOAPString
#   seat - SOAP::SOAPUnsignedByte
#   splitItemId - SOAP::SOAPShort
#   taxes - ArrayOfOrderEntryTax
class OrderItem < OrderEntry
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :price
  attr_accessor :promotions
  attr_accessor :comboItems
  attr_accessor :componentId
  attr_accessor :compositeOrderItemId
  attr_accessor :denominator
  attr_accessor :destinationId
  attr_accessor :discounts
  attr_accessor :modifiers
  attr_accessor :note
  attr_accessor :seat
  attr_accessor :splitItemId
  attr_accessor :taxes

  def initialize(description = nil, id = nil, itemId = nil, price = nil, promotions = nil, comboItems = nil, componentId = nil, compositeOrderItemId = nil, denominator = nil, destinationId = nil, discounts = nil, modifiers = nil, note = nil, seat = nil, splitItemId = nil, taxes = nil)
    @description = description
    @id = id
    @itemId = itemId
    @price = price
    @promotions = promotions
    @comboItems = comboItems
    @componentId = componentId
    @compositeOrderItemId = compositeOrderItemId
    @denominator = denominator
    @destinationId = destinationId
    @discounts = discounts
    @modifiers = modifiers
    @note = note
    @seat = seat
    @splitItemId = splitItemId
    @taxes = taxes
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderGiftCard
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   price - SOAP::SOAPDecimal
#   promotions - ArrayOfOrderEntryPromotion
class OrderGiftCard < OrderEntry
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :price
  attr_accessor :promotions

  def initialize(description = nil, id = nil, itemId = nil, price = nil, promotions = nil)
    @description = description
    @id = id
    @itemId = itemId
    @price = price
    @promotions = promotions
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderEntryPromotion
class ArrayOfOrderEntryPromotion < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderEntryPromotion
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   orderPromotionId - SOAP::SOAPInt
class OrderEntryPromotion
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :orderPromotionId

  def initialize(amount = nil, id = nil, orderPromotionId = nil)
    @amount = amount
    @id = id
    @orderPromotionId = orderPromotionId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderItem
class ArrayOfOrderItem < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderItemDiscount
class ArrayOfOrderItemDiscount < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderItemDiscount
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   orderDiscountId - SOAP::SOAPInt
class OrderItemDiscount
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :orderDiscountId

  def initialize(amount = nil, id = nil, orderDiscountId = nil)
    @amount = amount
    @id = id
    @orderDiscountId = orderDiscountId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderItemModifier
class ArrayOfOrderItemModifier < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderItemModifier
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   modifierCodeId - SOAP::SOAPInt
#   modifierGroupId - SOAP::SOAPInt
#   modifiers - ArrayOfOrderItemModifier
#   price - SOAP::SOAPDecimal
#   taxes - ArrayOfOrderEntryTax
class OrderItemModifier
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :modifierCodeId
  attr_accessor :modifierGroupId
  attr_accessor :modifiers
  attr_accessor :price
  attr_accessor :taxes

  def initialize(description = nil, id = nil, itemId = nil, modifierCodeId = nil, modifierGroupId = nil, modifiers = nil, price = nil, taxes = nil)
    @description = description
    @id = id
    @itemId = itemId
    @modifierCodeId = modifierCodeId
    @modifierGroupId = modifierGroupId
    @modifiers = modifiers
    @price = price
    @taxes = taxes
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderEntryTax
class ArrayOfOrderEntryTax < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderEntryTax
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   taxId - SOAP::SOAPInt
class OrderEntryTax
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :taxId

  def initialize(amount = nil, id = nil, taxId = nil)
    @amount = amount
    @id = id
    @taxId = taxId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}FutureOrderDetails
#   delivery - DeliveryDetails
#   emailAddress - SOAP::SOAPString
#   isCancelled - SOAP::SOAPBoolean
#   phoneNumber - SOAP::SOAPString
#   pickupTime - DateTimeOffset
class FutureOrderDetails
  attr_accessor :delivery
  attr_accessor :emailAddress
  attr_accessor :isCancelled
  attr_accessor :phoneNumber
  attr_accessor :pickupTime

  def initialize(delivery = nil, emailAddress = nil, isCancelled = nil, phoneNumber = nil, pickupTime = nil)
    @delivery = delivery
    @emailAddress = emailAddress
    @isCancelled = isCancelled
    @phoneNumber = phoneNumber
    @pickupTime = pickupTime
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}DeliveryDetails
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   city - SOAP::SOAPString
#   country - SOAP::SOAPString
#   postalCode - SOAP::SOAPString
#   stateCode - SOAP::SOAPString
class DeliveryDetails
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :city
  attr_accessor :country
  attr_accessor :postalCode
  attr_accessor :stateCode

  def initialize(address1 = nil, address2 = nil, city = nil, country = nil, postalCode = nil, stateCode = nil)
    @address1 = address1
    @address2 = address2
    @city = city
    @country = country
    @postalCode = postalCode
    @stateCode = stateCode
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderPayment
class ArrayOfOrderPayment < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderPayment
#   accountNumber - SOAP::SOAPString
#   accountType - SOAP::SOAPInt
#   amount - SOAP::SOAPDecimal
#   businessDate - SOAP::SOAPDateTime
#   cardHolderName - SOAP::SOAPString
#   creditCardTransactionInformation - CreditCardTransactionInformation
#   id - SOAP::SOAPInt
#   isDeposit - SOAP::SOAPBoolean
#   referenceNumber - SOAP::SOAPString
#   tenderId - SOAP::SOAPInt
#   time - DateTimeOffset
#   tipAmount - SOAP::SOAPDecimal
class OrderPayment
  attr_accessor :accountNumber
  attr_accessor :accountType
  attr_accessor :amount
  attr_accessor :businessDate
  attr_accessor :cardHolderName
  attr_accessor :creditCardTransactionInformation
  attr_accessor :id
  attr_accessor :isDeposit
  attr_accessor :referenceNumber
  attr_accessor :tenderId
  attr_accessor :time
  attr_accessor :tipAmount

  def initialize(accountNumber = nil, accountType = nil, amount = nil, businessDate = nil, cardHolderName = nil, creditCardTransactionInformation = nil, id = nil, isDeposit = nil, referenceNumber = nil, tenderId = nil, time = nil, tipAmount = nil)
    @accountNumber = accountNumber
    @accountType = accountType
    @amount = amount
    @businessDate = businessDate
    @cardHolderName = cardHolderName
    @creditCardTransactionInformation = creditCardTransactionInformation
    @id = id
    @isDeposit = isDeposit
    @referenceNumber = referenceNumber
    @tenderId = tenderId
    @time = time
    @tipAmount = tipAmount
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CreditCardTransactionInformation
#   authorizationCode - SOAP::SOAPString
#   cardToken - SOAP::SOAPString
#   clientTransactionIdentifier - SOAP::SOAPString
#   result - SOAP::SOAPString
class CreditCardTransactionInformation
  attr_accessor :authorizationCode
  attr_accessor :cardToken
  attr_accessor :clientTransactionIdentifier
  attr_accessor :result

  def initialize(authorizationCode = nil, cardToken = nil, clientTransactionIdentifier = nil, result = nil)
    @authorizationCode = authorizationCode
    @cardToken = cardToken
    @clientTransactionIdentifier = clientTransactionIdentifier
    @result = result
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderPromotion
class ArrayOfOrderPromotion < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderPromotion
#   amount - SOAP::SOAPDecimal
#   code - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   isSystemApplied - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   promotionId - SOAP::SOAPInt
class OrderPromotion
  attr_accessor :amount
  attr_accessor :code
  attr_accessor :id
  attr_accessor :isSystemApplied
  attr_accessor :name
  attr_accessor :promotionId

  def initialize(amount = nil, code = nil, id = nil, isSystemApplied = nil, name = nil, promotionId = nil)
    @amount = amount
    @code = code
    @id = id
    @isSystemApplied = isSystemApplied
    @name = name
    @promotionId = promotionId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfOrderSurcharge
class ArrayOfOrderSurcharge < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderSurcharge
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   isSystemApplied - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   surchargeId - SOAP::SOAPInt
#   taxes - ArrayOfOrderEntryTax
class OrderSurcharge
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :isSystemApplied
  attr_accessor :name
  attr_accessor :surchargeId
  attr_accessor :taxes

  def initialize(amount = nil, id = nil, isSystemApplied = nil, name = nil, surchargeId = nil, taxes = nil)
    @amount = amount
    @id = id
    @isSystemApplied = isSystemApplied
    @name = name
    @surchargeId = surchargeId
    @taxes = taxes
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CancelOrderRequest
#   orderId - SOAP::SOAPLong
#   suppressCancellationEmail - SOAP::SOAPBoolean
class CancelOrderRequest
  attr_accessor :orderId
  attr_accessor :suppressCancellationEmail

  def initialize(orderId = nil, suppressCancellationEmail = nil)
    @orderId = orderId
    @suppressCancellationEmail = suppressCancellationEmail
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetItemAvailabilityRequest
#   itemIds - ArrayOfint
class GetItemAvailabilityRequest
  attr_accessor :itemIds

  def initialize(itemIds = nil)
    @itemIds = itemIds
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ArrayOfItemAvailabilityDetail
class ArrayOfItemAvailabilityDetail < ::Array
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}ItemAvailabilityDetail
#   isAvailable - SOAP::SOAPBoolean
#   itemId - SOAP::SOAPInt
#   quantityAvailable - SOAP::SOAPInt
class ItemAvailabilityDetail
  attr_accessor :isAvailable
  attr_accessor :itemId
  attr_accessor :quantityAvailable

  def initialize(isAvailable = nil, itemId = nil, quantityAvailable = nil)
    @isAvailable = isAvailable
    @itemId = itemId
    @quantityAvailable = quantityAvailable
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetOrderRequest
#   orderId - SOAP::SOAPLong
class GetOrderRequest
  attr_accessor :orderId

  def initialize(orderId = nil)
    @orderId = orderId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}SubmitOrderRequest
#   options - OrderingOptions
#   order - NewOrder
#   suppressConfirmationEmail - SOAP::SOAPBoolean
class SubmitOrderRequest
  attr_accessor :options
  attr_accessor :order
  attr_accessor :suppressConfirmationEmail

  def initialize(options = nil, order = nil, suppressConfirmationEmail = nil)
    @options = options
    @order = order
    @suppressConfirmationEmail = suppressConfirmationEmail
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}UpdateItemAvailabilityRequest
#   details - ArrayOfItemAvailabilityDetail
class UpdateItemAvailabilityRequest
  attr_accessor :details

  def initialize(details = nil)
    @details = details
  end
end

# {http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfint
class ArrayOfint < ::Array
end

# {http://schemas.datacontract.org/2004/07/System}DateTimeOffset
#   dateTime - SOAP::SOAPDateTime
#   offsetMinutes - SOAP::SOAPShort
class DateTimeOffset
  attr_accessor :dateTime
  attr_accessor :offsetMinutes

  def initialize(dateTime = nil, offsetMinutes = nil)
    @dateTime = dateTime
    @offsetMinutes = offsetMinutes
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service}Reply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class Reply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}OrderingWebServiceReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class OrderingWebServiceReply < Reply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CalculateOrderReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   order - Order
class CalculateOrderReply < OrderingWebServiceReply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :order

  def initialize(message = nil, resultCode = nil, order = nil)
    @message = message
    @resultCode = resultCode
    @order = order
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CancelOrderReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class CancelOrderReply < OrderingWebServiceReply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetItemAvailabilityReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   details - ArrayOfItemAvailabilityDetail
class GetItemAvailabilityReply < OrderingWebServiceReply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :details

  def initialize(message = nil, resultCode = nil, details = nil)
    @message = message
    @resultCode = resultCode
    @details = details
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetMasterTerminalStatusReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   status - SOAP::SOAPUnsignedByte
class GetMasterTerminalStatusReply < OrderingWebServiceReply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :status

  def initialize(message = nil, resultCode = nil, status = nil)
    @message = message
    @resultCode = resultCode
    @status = status
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetOrderReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   order - Order
class GetOrderReply < OrderingWebServiceReply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :order

  def initialize(message = nil, resultCode = nil, order = nil)
    @message = message
    @resultCode = resultCode
    @order = order
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}SubmitOrderReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   orderId - SOAP::SOAPLong
class SubmitOrderReply < OrderingWebServiceReply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :orderId

  def initialize(message = nil, resultCode = nil, orderId = nil)
    @message = message
    @resultCode = resultCode
    @orderId = orderId
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}UpdateItemAvailabilityReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class UpdateItemAvailabilityReply < OrderingWebServiceReply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CalculateOrder
#   request - CalculateOrderRequest
class CalculateOrder
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CalculateOrderResponse
#   calculateOrderResult - CalculateOrderReply
class CalculateOrderResponse
  attr_accessor :calculateOrderResult

  def initialize(calculateOrderResult = nil)
    @calculateOrderResult = calculateOrderResult
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CancelOrder
#   request - CancelOrderRequest
class CancelOrder
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}CancelOrderResponse
#   cancelOrderResult - CancelOrderReply
class CancelOrderResponse
  attr_accessor :cancelOrderResult

  def initialize(cancelOrderResult = nil)
    @cancelOrderResult = cancelOrderResult
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetItemAvailability
#   request - GetItemAvailabilityRequest
class GetItemAvailability
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetItemAvailabilityResponse
#   getItemAvailabilityResult - GetItemAvailabilityReply
class GetItemAvailabilityResponse
  attr_accessor :getItemAvailabilityResult

  def initialize(getItemAvailabilityResult = nil)
    @getItemAvailabilityResult = getItemAvailabilityResult
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetMasterTerminalStatus
class GetMasterTerminalStatus
  def initialize
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetMasterTerminalStatusResponse
#   getMasterTerminalStatusResult - GetMasterTerminalStatusReply
class GetMasterTerminalStatusResponse
  attr_accessor :getMasterTerminalStatusResult

  def initialize(getMasterTerminalStatusResult = nil)
    @getMasterTerminalStatusResult = getMasterTerminalStatusResult
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetOrder
#   request - GetOrderRequest
class GetOrder
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}GetOrderResponse
#   getOrderResult - GetOrderReply
class GetOrderResponse
  attr_accessor :getOrderResult

  def initialize(getOrderResult = nil)
    @getOrderResult = getOrderResult
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}SubmitOrder
#   request - SubmitOrderRequest
class SubmitOrder
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}SubmitOrderResponse
#   submitOrderResult - SubmitOrderReply
class SubmitOrderResponse
  attr_accessor :submitOrderResult

  def initialize(submitOrderResult = nil)
    @submitOrderResult = submitOrderResult
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}UpdateItemAvailability
#   request - UpdateItemAvailabilityRequest
class UpdateItemAvailability
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/ordering/20140219}UpdateItemAvailabilityResponse
#   updateItemAvailabilityResult - UpdateItemAvailabilityReply
class UpdateItemAvailabilityResponse
  attr_accessor :updateItemAvailabilityResult

  def initialize(updateItemAvailabilityResult = nil)
    @updateItemAvailabilityResult = updateItemAvailabilityResult
  end
end
