# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require 'xsd/qname'

# {http://www.brinksoftware.com/webservices/sales/v2}GetDepositsRequest
#   businessDate - SOAP::SOAPDateTime
class GetDepositsRequest
  attr_accessor :businessDate

  def initialize(businessDate = nil)
    @businessDate = businessDate
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfDeposit
class ArrayOfDeposit < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}Deposit
#   amount - SOAP::SOAPDecimal
#   bag - SOAP::SOAPString
#   businessDate - SOAP::SOAPDateTime
#   depositTypeId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   notes - SOAP::SOAPString
#   number - SOAP::SOAPInt
#   time - DateTimeOffset
class Deposit
  attr_accessor :amount
  attr_accessor :bag
  attr_accessor :businessDate
  attr_accessor :depositTypeId
  attr_accessor :id
  attr_accessor :notes
  attr_accessor :number
  attr_accessor :time

  def initialize(amount = nil, bag = nil, businessDate = nil, depositTypeId = nil, id = nil, notes = nil, number = nil, time = nil)
    @amount = amount
    @bag = bag
    @businessDate = businessDate
    @depositTypeId = depositTypeId
    @id = id
    @notes = notes
    @number = number
    @time = time
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrderDepositsRequest
#   businessDate - SOAP::SOAPDateTime
class GetFutureDateOrderDepositsRequest
  attr_accessor :businessDate

  def initialize(businessDate = nil)
    @businessDate = businessDate
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfFutureDateOrderDeposit
class ArrayOfFutureDateOrderDeposit < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}FutureDateOrderDeposit
#   amount - SOAP::SOAPDecimal
#   authCode - SOAP::SOAPString
#   businessDate - SOAP::SOAPDateTime
#   cardHolderName - SOAP::SOAPString
#   cardNumber - SOAP::SOAPString
#   employeeId - SOAP::SOAPInt
#   merchantAccountType - SOAP::SOAPInt
#   orderId - SOAP::SOAPLong
#   orderTotal - SOAP::SOAPDecimal
#   paymentId - SOAP::SOAPInt
#   sectionId - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tillNumber - SOAP::SOAPInt
#   time - DateTimeOffset
class FutureDateOrderDeposit
  attr_accessor :amount
  attr_accessor :authCode
  attr_accessor :businessDate
  attr_accessor :cardHolderName
  attr_accessor :cardNumber
  attr_accessor :employeeId
  attr_accessor :merchantAccountType
  attr_accessor :orderId
  attr_accessor :orderTotal
  attr_accessor :paymentId
  attr_accessor :sectionId
  attr_accessor :tenderId
  attr_accessor :tillNumber
  attr_accessor :time

  def initialize(amount = nil, authCode = nil, businessDate = nil, cardHolderName = nil, cardNumber = nil, employeeId = nil, merchantAccountType = nil, orderId = nil, orderTotal = nil, paymentId = nil, sectionId = nil, tenderId = nil, tillNumber = nil, time = nil)
    @amount = amount
    @authCode = authCode
    @businessDate = businessDate
    @cardHolderName = cardHolderName
    @cardNumber = cardNumber
    @employeeId = employeeId
    @merchantAccountType = merchantAccountType
    @orderId = orderId
    @orderTotal = orderTotal
    @paymentId = paymentId
    @sectionId = sectionId
    @tenderId = tenderId
    @tillNumber = tillNumber
    @time = time
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrdersRequest
#   futureDateRange - DateRange
#   priceRollUp - SOAP::SOAPString
class GetFutureDateOrdersRequest
  attr_accessor :futureDateRange
  attr_accessor :priceRollUp

  def initialize(futureDateRange = nil, priceRollUp = nil)
    @futureDateRange = futureDateRange
    @priceRollUp = priceRollUp
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrder
class ArrayOfOrder < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}Order
#   businessDate - SOAP::SOAPDateTime
#   closedTime - DateTimeOffset
#   count - SOAP::SOAPInt
#   customerId - (any)
#   deposits - ArrayOfOrderDeposit
#   destinationId - SOAP::SOAPInt
#   discounts - ArrayOfOrderDiscount
#   displaySubtotal - SOAP::SOAPDecimal
#   displayTax - SOAP::SOAPDecimal
#   employeeId - SOAP::SOAPInt
#   entries - ArrayOfOrderEntry
#   firstSendTime - DateTimeOffset
#   grossSales - SOAP::SOAPDecimal
#   guestCount - SOAP::SOAPInt
#   guestCountFractional - SOAP::SOAPDecimal
#   id - SOAP::SOAPLong
#   idEncoded - SOAP::SOAPString
#   idNoLocation - SOAP::SOAPInt
#   isClosed - SOAP::SOAPBoolean
#   isFutureOrder - SOAP::SOAPBoolean
#   isRefund - SOAP::SOAPBoolean
#   isTaxExempt - SOAP::SOAPBoolean
#   modifiedTime - DateTimeOffset
#   name - SOAP::SOAPString
#   netSales - SOAP::SOAPDecimal
#   openedTime - DateTimeOffset
#   payments - ArrayOfOrderPayment
#   pickupTime - SOAP::SOAPDateTime
#   promotions - ArrayOfOrderPromotion
#   rounding - SOAP::SOAPDecimal
#   sectionId - SOAP::SOAPInt
#   subtotal - SOAP::SOAPDecimal
#   surcharges - ArrayOfOrderSurcharge
#   tax - SOAP::SOAPDecimal
#   taxExemptId - SOAP::SOAPString
#   terminalId - SOAP::SOAPInt
#   tillNumber - SOAP::SOAPInt
#   total - SOAP::SOAPDecimal
class Order
  attr_accessor :businessDate
  attr_accessor :closedTime
  attr_accessor :count
  attr_accessor :customerId
  attr_accessor :deposits
  attr_accessor :destinationId
  attr_accessor :discounts
  attr_accessor :displaySubtotal
  attr_accessor :displayTax
  attr_accessor :employeeId
  attr_accessor :entries
  attr_accessor :firstSendTime
  attr_accessor :grossSales
  attr_accessor :guestCount
  attr_accessor :guestCountFractional
  attr_accessor :id
  attr_accessor :idEncoded
  attr_accessor :idNoLocation
  attr_accessor :isClosed
  attr_accessor :isFutureOrder
  attr_accessor :isRefund
  attr_accessor :isTaxExempt
  attr_accessor :modifiedTime
  attr_accessor :name
  attr_accessor :netSales
  attr_accessor :openedTime
  attr_accessor :payments
  attr_accessor :pickupTime
  attr_accessor :promotions
  attr_accessor :rounding
  attr_accessor :sectionId
  attr_accessor :subtotal
  attr_accessor :surcharges
  attr_accessor :tax
  attr_accessor :taxExemptId
  attr_accessor :terminalId
  attr_accessor :tillNumber
  attr_accessor :total

  def initialize(businessDate = nil, closedTime = nil, count = nil, customerId = nil, deposits = nil, destinationId = nil, discounts = nil, displaySubtotal = nil, displayTax = nil, employeeId = nil, entries = nil, firstSendTime = nil, grossSales = nil, guestCount = nil, guestCountFractional = nil, id = nil, idEncoded = nil, idNoLocation = nil, isClosed = nil, isFutureOrder = nil, isRefund = nil, isTaxExempt = nil, modifiedTime = nil, name = nil, netSales = nil, openedTime = nil, payments = nil, pickupTime = nil, promotions = nil, rounding = nil, sectionId = nil, subtotal = nil, surcharges = nil, tax = nil, taxExemptId = nil, terminalId = nil, tillNumber = nil, total = nil)
    @businessDate = businessDate
    @closedTime = closedTime
    @count = count
    @customerId = customerId
    @deposits = deposits
    @destinationId = destinationId
    @discounts = discounts
    @displaySubtotal = displaySubtotal
    @displayTax = displayTax
    @employeeId = employeeId
    @entries = entries
    @firstSendTime = firstSendTime
    @grossSales = grossSales
    @guestCount = guestCount
    @guestCountFractional = guestCountFractional
    @id = id
    @idEncoded = idEncoded
    @idNoLocation = idNoLocation
    @isClosed = isClosed
    @isFutureOrder = isFutureOrder
    @isRefund = isRefund
    @isTaxExempt = isTaxExempt
    @modifiedTime = modifiedTime
    @name = name
    @netSales = netSales
    @openedTime = openedTime
    @payments = payments
    @pickupTime = pickupTime
    @promotions = promotions
    @rounding = rounding
    @sectionId = sectionId
    @subtotal = subtotal
    @surcharges = surcharges
    @tax = tax
    @taxExemptId = taxExemptId
    @terminalId = terminalId
    @tillNumber = tillNumber
    @total = total
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderDeposit
class ArrayOfOrderDeposit < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderDeposit
#   amount - SOAP::SOAPDecimal
#   businessDate - SOAP::SOAPDateTime
#   employeeId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   isApplied - SOAP::SOAPBoolean
#   isDeleted - SOAP::SOAPBoolean
#   isReversal - SOAP::SOAPBoolean
#   originalOrderDepositId - SOAP::SOAPInt
#   paymentId - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
class OrderDeposit
  attr_accessor :amount
  attr_accessor :businessDate
  attr_accessor :employeeId
  attr_accessor :id
  attr_accessor :isApplied
  attr_accessor :isDeleted
  attr_accessor :isReversal
  attr_accessor :originalOrderDepositId
  attr_accessor :paymentId
  attr_accessor :tenderId

  def initialize(amount = nil, businessDate = nil, employeeId = nil, id = nil, isApplied = nil, isDeleted = nil, isReversal = nil, originalOrderDepositId = nil, paymentId = nil, tenderId = nil)
    @amount = amount
    @businessDate = businessDate
    @employeeId = employeeId
    @id = id
    @isApplied = isApplied
    @isDeleted = isDeleted
    @isReversal = isReversal
    @originalOrderDepositId = originalOrderDepositId
    @paymentId = paymentId
    @tenderId = tenderId
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderDiscount
class ArrayOfOrderDiscount < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderDiscount
#   amount - SOAP::SOAPDecimal
#   approverEmployeeId - SOAP::SOAPInt
#   discountId - SOAP::SOAPInt
#   employeeId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   loyaltyRewardId - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   source - SOAP::SOAPInt
class OrderDiscount
  attr_accessor :amount
  attr_accessor :approverEmployeeId
  attr_accessor :discountId
  attr_accessor :employeeId
  attr_accessor :id
  attr_accessor :loyaltyRewardId
  attr_accessor :name
  attr_accessor :source

  def initialize(amount = nil, approverEmployeeId = nil, discountId = nil, employeeId = nil, id = nil, loyaltyRewardId = nil, name = nil, source = nil)
    @amount = amount
    @approverEmployeeId = approverEmployeeId
    @discountId = discountId
    @employeeId = employeeId
    @id = id
    @loyaltyRewardId = loyaltyRewardId
    @name = name
    @source = source
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderEntry
class ArrayOfOrderEntry < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderEntry
#   dayPartId - SOAP::SOAPInt
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   price - SOAP::SOAPDecimal
#   promotions - ArrayOfOrderEntryPromotion
class OrderEntry
  attr_accessor :dayPartId
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :price
  attr_accessor :promotions

  def initialize(dayPartId = nil, description = nil, id = nil, itemId = nil, price = nil, promotions = nil)
    @dayPartId = dayPartId
    @description = description
    @id = id
    @itemId = itemId
    @price = price
    @promotions = promotions
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderItem
#   dayPartId - SOAP::SOAPInt
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   price - SOAP::SOAPDecimal
#   promotions - ArrayOfOrderEntryPromotion
#   compositeOrderItemId - SOAP::SOAPInt
#   denominator - SOAP::SOAPUnsignedByte
#   destinationId - SOAP::SOAPInt
#   discounts - ArrayOfOrderItemDiscount
#   displayPrice - SOAP::SOAPDecimal
#   grossSales - SOAP::SOAPDecimal
#   isCleared - SOAP::SOAPBoolean
#   isDeleted - SOAP::SOAPBoolean
#   isVoided - SOAP::SOAPBoolean
#   itemGrossSales - SOAP::SOAPDecimal
#   itemNetSales - SOAP::SOAPDecimal
#   modifiers - ArrayOfOrderItemModifier
#   netSales - SOAP::SOAPDecimal
#   note - SOAP::SOAPString
#   splitItemId - SOAP::SOAPShort
#   taxes - ArrayOfOrderEntryTax
#   void - OrderItemVoid
class OrderItem < OrderEntry
  attr_accessor :dayPartId
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :price
  attr_accessor :promotions
  attr_accessor :compositeOrderItemId
  attr_accessor :denominator
  attr_accessor :destinationId
  attr_accessor :discounts
  attr_accessor :displayPrice
  attr_accessor :grossSales
  attr_accessor :isCleared
  attr_accessor :isDeleted
  attr_accessor :isVoided
  attr_accessor :itemGrossSales
  attr_accessor :itemNetSales
  attr_accessor :modifiers
  attr_accessor :netSales
  attr_accessor :note
  attr_accessor :splitItemId
  attr_accessor :taxes
  attr_accessor :void

  def initialize(dayPartId = nil, description = nil, id = nil, itemId = nil, price = nil, promotions = nil, compositeOrderItemId = nil, denominator = nil, destinationId = nil, discounts = nil, displayPrice = nil, grossSales = nil, isCleared = nil, isDeleted = nil, isVoided = nil, itemGrossSales = nil, itemNetSales = nil, modifiers = nil, netSales = nil, note = nil, splitItemId = nil, taxes = nil, void = nil)
    @dayPartId = dayPartId
    @description = description
    @id = id
    @itemId = itemId
    @price = price
    @promotions = promotions
    @compositeOrderItemId = compositeOrderItemId
    @denominator = denominator
    @destinationId = destinationId
    @discounts = discounts
    @displayPrice = displayPrice
    @grossSales = grossSales
    @isCleared = isCleared
    @isDeleted = isDeleted
    @isVoided = isVoided
    @itemGrossSales = itemGrossSales
    @itemNetSales = itemNetSales
    @modifiers = modifiers
    @netSales = netSales
    @note = note
    @splitItemId = splitItemId
    @taxes = taxes
    @void = void
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderGiftCard
#   dayPartId - SOAP::SOAPInt
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   itemId - SOAP::SOAPInt
#   price - SOAP::SOAPDecimal
#   promotions - ArrayOfOrderEntryPromotion
class OrderGiftCard < OrderEntry
  attr_accessor :dayPartId
  attr_accessor :description
  attr_accessor :id
  attr_accessor :itemId
  attr_accessor :price
  attr_accessor :promotions

  def initialize(dayPartId = nil, description = nil, id = nil, itemId = nil, price = nil, promotions = nil)
    @dayPartId = dayPartId
    @description = description
    @id = id
    @itemId = itemId
    @price = price
    @promotions = promotions
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderEntryPromotion
class ArrayOfOrderEntryPromotion < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderEntryPromotion
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   orderPromotionId - SOAP::SOAPInt
class OrderEntryPromotion
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :orderPromotionId

  def initialize(amount = nil, id = nil, orderPromotionId = nil)
    @amount = amount
    @id = id
    @orderPromotionId = orderPromotionId
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderItemDiscount
class ArrayOfOrderItemDiscount < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderItemDiscount
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   orderDiscountId - SOAP::SOAPInt
class OrderItemDiscount
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :orderDiscountId

  def initialize(amount = nil, id = nil, orderDiscountId = nil)
    @amount = amount
    @id = id
    @orderDiscountId = orderDiscountId
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderItemModifier
class ArrayOfOrderItemModifier < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderItemModifier
#   displayPrice - SOAP::SOAPDecimal
#   grossSales - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   itemGrossSales - SOAP::SOAPDecimal
#   itemId - SOAP::SOAPInt
#   itemNetSales - SOAP::SOAPDecimal
#   modifierCodeId - SOAP::SOAPInt
#   modifierGroupId - SOAP::SOAPInt
#   modifiers - ArrayOfOrderItemModifier
#   netSales - SOAP::SOAPDecimal
#   price - SOAP::SOAPDecimal
#   taxes - ArrayOfOrderEntryTax
class OrderItemModifier
  attr_accessor :displayPrice
  attr_accessor :grossSales
  attr_accessor :id
  attr_accessor :itemGrossSales
  attr_accessor :itemId
  attr_accessor :itemNetSales
  attr_accessor :modifierCodeId
  attr_accessor :modifierGroupId
  attr_accessor :modifiers
  attr_accessor :netSales
  attr_accessor :price
  attr_accessor :taxes

  def initialize(displayPrice = nil, grossSales = nil, id = nil, itemGrossSales = nil, itemId = nil, itemNetSales = nil, modifierCodeId = nil, modifierGroupId = nil, modifiers = nil, netSales = nil, price = nil, taxes = nil)
    @displayPrice = displayPrice
    @grossSales = grossSales
    @id = id
    @itemGrossSales = itemGrossSales
    @itemId = itemId
    @itemNetSales = itemNetSales
    @modifierCodeId = modifierCodeId
    @modifierGroupId = modifierGroupId
    @modifiers = modifiers
    @netSales = netSales
    @price = price
    @taxes = taxes
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderEntryTax
class ArrayOfOrderEntryTax < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderEntryTax
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   isInclusive - SOAP::SOAPBoolean
#   taxId - SOAP::SOAPInt
class OrderEntryTax
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :isInclusive
  attr_accessor :taxId

  def initialize(amount = nil, id = nil, isInclusive = nil, taxId = nil)
    @amount = amount
    @id = id
    @isInclusive = isInclusive
    @taxId = taxId
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderItemVoid
#   approverEmployeeId - SOAP::SOAPInt
#   employeeId - SOAP::SOAPInt
#   time - DateTimeOffset
#   voidReasonId - SOAP::SOAPInt
class OrderItemVoid
  attr_accessor :approverEmployeeId
  attr_accessor :employeeId
  attr_accessor :time
  attr_accessor :voidReasonId

  def initialize(approverEmployeeId = nil, employeeId = nil, time = nil, voidReasonId = nil)
    @approverEmployeeId = approverEmployeeId
    @employeeId = employeeId
    @time = time
    @voidReasonId = voidReasonId
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderPayment
class ArrayOfOrderPayment < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderPayment
#   amount - SOAP::SOAPDecimal
#   businessDate - SOAP::SOAPDateTime
#   cardHolderName - SOAP::SOAPString
#   cardNumber - SOAP::SOAPString
#   change - SOAP::SOAPDecimal
#   creditCardTransactionInformation - CreditCardTransactionInformation
#   details - ArrayOfOrderPaymentDetail
#   employeeId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   merchantAccountType - SOAP::SOAPInt
#   tenderId - SOAP::SOAPInt
#   tillNumber - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
class OrderPayment
  attr_accessor :amount
  attr_accessor :businessDate
  attr_accessor :cardHolderName
  attr_accessor :cardNumber
  attr_accessor :change
  attr_accessor :creditCardTransactionInformation
  attr_accessor :details
  attr_accessor :employeeId
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :merchantAccountType
  attr_accessor :tenderId
  attr_accessor :tillNumber
  attr_accessor :tipAmount

  def initialize(amount = nil, businessDate = nil, cardHolderName = nil, cardNumber = nil, change = nil, creditCardTransactionInformation = nil, details = nil, employeeId = nil, id = nil, isDeleted = nil, merchantAccountType = nil, tenderId = nil, tillNumber = nil, tipAmount = nil)
    @amount = amount
    @businessDate = businessDate
    @cardHolderName = cardHolderName
    @cardNumber = cardNumber
    @change = change
    @creditCardTransactionInformation = creditCardTransactionInformation
    @details = details
    @employeeId = employeeId
    @id = id
    @isDeleted = isDeleted
    @merchantAccountType = merchantAccountType
    @tenderId = tenderId
    @tillNumber = tillNumber
    @tipAmount = tipAmount
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}CreditCardTransactionInformation
#   authorizationCode - SOAP::SOAPString
#   cardToken - SOAP::SOAPString
#   clientTransactionIdentifier - SOAP::SOAPString
#   result - SOAP::SOAPString
class CreditCardTransactionInformation
  attr_accessor :authorizationCode
  attr_accessor :cardToken
  attr_accessor :clientTransactionIdentifier
  attr_accessor :result

  def initialize(authorizationCode = nil, cardToken = nil, clientTransactionIdentifier = nil, result = nil)
    @authorizationCode = authorizationCode
    @cardToken = cardToken
    @clientTransactionIdentifier = clientTransactionIdentifier
    @result = result
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderPaymentDetail
class ArrayOfOrderPaymentDetail < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderPaymentDetail
#   amount - SOAP::SOAPDecimal
#   employeeId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   tillNumber - SOAP::SOAPInt
#   tipAmount - SOAP::SOAPDecimal
#   type - SOAP::SOAPInt
class OrderPaymentDetail
  attr_accessor :amount
  attr_accessor :employeeId
  attr_accessor :id
  attr_accessor :tillNumber
  attr_accessor :tipAmount
  attr_accessor :type

  def initialize(amount = nil, employeeId = nil, id = nil, tillNumber = nil, tipAmount = nil, type = nil)
    @amount = amount
    @employeeId = employeeId
    @id = id
    @tillNumber = tillNumber
    @tipAmount = tipAmount
    @type = type
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderPromotion
class ArrayOfOrderPromotion < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderPromotion
#   amount - SOAP::SOAPDecimal
#   approverEmployeeId - SOAP::SOAPInt
#   employeeId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   promotionId - SOAP::SOAPInt
class OrderPromotion
  attr_accessor :amount
  attr_accessor :approverEmployeeId
  attr_accessor :employeeId
  attr_accessor :id
  attr_accessor :name
  attr_accessor :promotionId

  def initialize(amount = nil, approverEmployeeId = nil, employeeId = nil, id = nil, name = nil, promotionId = nil)
    @amount = amount
    @approverEmployeeId = approverEmployeeId
    @employeeId = employeeId
    @id = id
    @name = name
    @promotionId = promotionId
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfOrderSurcharge
class ArrayOfOrderSurcharge < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}OrderSurcharge
#   amount - SOAP::SOAPDecimal
#   approverEmployeeId - SOAP::SOAPInt
#   employeeId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   isSystemApplied - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   surchargeId - SOAP::SOAPInt
#   taxes - ArrayOfOrderEntryTax
class OrderSurcharge
  attr_accessor :amount
  attr_accessor :approverEmployeeId
  attr_accessor :employeeId
  attr_accessor :id
  attr_accessor :isSystemApplied
  attr_accessor :name
  attr_accessor :surchargeId
  attr_accessor :taxes

  def initialize(amount = nil, approverEmployeeId = nil, employeeId = nil, id = nil, isSystemApplied = nil, name = nil, surchargeId = nil, taxes = nil)
    @amount = amount
    @approverEmployeeId = approverEmployeeId
    @employeeId = employeeId
    @id = id
    @isSystemApplied = isSystemApplied
    @name = name
    @surchargeId = surchargeId
    @taxes = taxes
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetOrdersRequest
#   businessDate - SOAP::SOAPDateTime
#   excludeOpenOrders - SOAP::SOAPBoolean
#   modifiedTime - DateTimeOffset
#   priceRollUp - SOAP::SOAPString
class GetOrdersRequest
  attr_accessor :businessDate
  attr_accessor :excludeOpenOrders
  attr_accessor :modifiedTime
  attr_accessor :priceRollUp

  def initialize(businessDate = nil, excludeOpenOrders = nil, modifiedTime = nil, priceRollUp = nil)
    @businessDate = businessDate
    @excludeOpenOrders = excludeOpenOrders
    @modifiedTime = modifiedTime
    @priceRollUp = priceRollUp
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetTillsRequest
#   businessDate - SOAP::SOAPDateTime
class GetTillsRequest
  attr_accessor :businessDate

  def initialize(businessDate = nil)
    @businessDate = businessDate
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfTill
class ArrayOfTill < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}Till
#   businessDate - SOAP::SOAPDateTime
#   cashDrawerId - SOAP::SOAPInt
#   closedByEmployeeId - SOAP::SOAPInt
#   closedTime - DateTimeOffset
#   declaredCash - SOAP::SOAPDecimal
#   employeeId - SOAP::SOAPInt
#   isClosed - SOAP::SOAPBoolean
#   isPublic - SOAP::SOAPBoolean
#   isVirtual - SOAP::SOAPBoolean
#   number - SOAP::SOAPInt
#   openedTime - DateTimeOffset
#   overShort - SOAP::SOAPDecimal
#   paidInOuts - ArrayOfPaidInOut
#   startingBank - SOAP::SOAPDecimal
class Till
  attr_accessor :businessDate
  attr_accessor :cashDrawerId
  attr_accessor :closedByEmployeeId
  attr_accessor :closedTime
  attr_accessor :declaredCash
  attr_accessor :employeeId
  attr_accessor :isClosed
  attr_accessor :isPublic
  attr_accessor :isVirtual
  attr_accessor :number
  attr_accessor :openedTime
  attr_accessor :overShort
  attr_accessor :paidInOuts
  attr_accessor :startingBank

  def initialize(businessDate = nil, cashDrawerId = nil, closedByEmployeeId = nil, closedTime = nil, declaredCash = nil, employeeId = nil, isClosed = nil, isPublic = nil, isVirtual = nil, number = nil, openedTime = nil, overShort = nil, paidInOuts = nil, startingBank = nil)
    @businessDate = businessDate
    @cashDrawerId = cashDrawerId
    @closedByEmployeeId = closedByEmployeeId
    @closedTime = closedTime
    @declaredCash = declaredCash
    @employeeId = employeeId
    @isClosed = isClosed
    @isPublic = isPublic
    @isVirtual = isVirtual
    @number = number
    @openedTime = openedTime
    @overShort = overShort
    @paidInOuts = paidInOuts
    @startingBank = startingBank
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}ArrayOfPaidInOut
class ArrayOfPaidInOut < ::Array
end

# {http://www.brinksoftware.com/webservices/sales/v2}PaidInOut
#   accountType - SOAP::SOAPInt
#   amount - SOAP::SOAPDecimal
#   description - SOAP::SOAPString
#   employeeId - SOAP::SOAPInt
#   number - SOAP::SOAPInt
#   pettyAccountId - SOAP::SOAPInt
#   time - DateTimeOffset
class PaidInOut
  attr_accessor :accountType
  attr_accessor :amount
  attr_accessor :description
  attr_accessor :employeeId
  attr_accessor :number
  attr_accessor :pettyAccountId
  attr_accessor :time

  def initialize(accountType = nil, amount = nil, description = nil, employeeId = nil, number = nil, pettyAccountId = nil, time = nil)
    @accountType = accountType
    @amount = amount
    @description = description
    @employeeId = employeeId
    @number = number
    @pettyAccountId = pettyAccountId
    @time = time
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service}Reply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
class Reply
  attr_accessor :message
  attr_accessor :resultCode

  def initialize(message = nil, resultCode = nil)
    @message = message
    @resultCode = resultCode
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetCurrentBusinessDateReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   businessDate - SOAP::SOAPDateTime
class GetCurrentBusinessDateReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :businessDate

  def initialize(message = nil, resultCode = nil, businessDate = nil)
    @message = message
    @resultCode = resultCode
    @businessDate = businessDate
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetDepositsReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   deposits - ArrayOfDeposit
class GetDepositsReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :deposits

  def initialize(message = nil, resultCode = nil, deposits = nil)
    @message = message
    @resultCode = resultCode
    @deposits = deposits
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrderDepositsReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   deposits - ArrayOfFutureDateOrderDeposit
class GetFutureDateOrderDepositsReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :deposits

  def initialize(message = nil, resultCode = nil, deposits = nil)
    @message = message
    @resultCode = resultCode
    @deposits = deposits
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrdersReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   futureDateOrders - ArrayOfOrder
class GetFutureDateOrdersReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :futureDateOrders

  def initialize(message = nil, resultCode = nil, futureDateOrders = nil)
    @message = message
    @resultCode = resultCode
    @futureDateOrders = futureDateOrders
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetOrdersReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   orders - ArrayOfOrder
class GetOrdersReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :orders

  def initialize(message = nil, resultCode = nil, orders = nil)
    @message = message
    @resultCode = resultCode
    @orders = orders
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetTillsReply
#   message - SOAP::SOAPString
#   resultCode - SOAP::SOAPInt
#   tills - ArrayOfTill
class GetTillsReply < Reply
  attr_accessor :message
  attr_accessor :resultCode
  attr_accessor :tills

  def initialize(message = nil, resultCode = nil, tills = nil)
    @message = message
    @resultCode = resultCode
    @tills = tills
  end
end

# {http://schemas.datacontract.org/2004/07/System}DateTimeOffset
#   dateTime - SOAP::SOAPDateTime
#   offsetMinutes - SOAP::SOAPShort
class DateTimeOffset
  attr_accessor :dateTime
  attr_accessor :offsetMinutes

  def initialize(dateTime = nil, offsetMinutes = nil)
    @dateTime = dateTime
    @offsetMinutes = offsetMinutes
  end
end

# {http://schemas.datacontract.org/2004/07/Brink.Foundation}DateRange
#   m_end - SOAP::SOAPDateTime
#   start - SOAP::SOAPDateTime
class DateRange
  attr_accessor :start

  def m_end
    @v_end
  end

  def m_end=(value)
    @v_end = value
  end

  def initialize(v_end = nil, start = nil)
    @v_end = v_end
    @start = start
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetCurrentBusinessDate
class GetCurrentBusinessDate
  def initialize
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetCurrentBusinessDateResponse
#   getCurrentBusinessDateResult - GetCurrentBusinessDateReply
class GetCurrentBusinessDateResponse
  attr_accessor :getCurrentBusinessDateResult

  def initialize(getCurrentBusinessDateResult = nil)
    @getCurrentBusinessDateResult = getCurrentBusinessDateResult
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetDeposits
#   request - GetDepositsRequest
class GetDeposits
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetDepositsResponse
#   getDepositsResult - GetDepositsReply
class GetDepositsResponse
  attr_accessor :getDepositsResult

  def initialize(getDepositsResult = nil)
    @getDepositsResult = getDepositsResult
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrderDeposits
#   request - GetFutureDateOrderDepositsRequest
class GetFutureDateOrderDeposits
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrderDepositsResponse
#   getFutureDateOrderDepositsResult - GetFutureDateOrderDepositsReply
class GetFutureDateOrderDepositsResponse
  attr_accessor :getFutureDateOrderDepositsResult

  def initialize(getFutureDateOrderDepositsResult = nil)
    @getFutureDateOrderDepositsResult = getFutureDateOrderDepositsResult
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrders
#   request - GetFutureDateOrdersRequest
class GetFutureDateOrders
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrdersResponse
#   getFutureDateOrdersResult - GetFutureDateOrdersReply
class GetFutureDateOrdersResponse
  attr_accessor :getFutureDateOrdersResult

  def initialize(getFutureDateOrdersResult = nil)
    @getFutureDateOrdersResult = getFutureDateOrdersResult
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetOrders
#   request - GetOrdersRequest
class GetOrders
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetOrdersResponse
#   getOrdersResult - GetOrdersReply
class GetOrdersResponse
  attr_accessor :getOrdersResult

  def initialize(getOrdersResult = nil)
    @getOrdersResult = getOrdersResult
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetTills
#   request - GetTillsRequest
class GetTills
  attr_accessor :request

  def initialize(request = nil)
    @request = request
  end
end

# {http://www.brinksoftware.com/webservices/sales/v2}GetTillsResponse
#   getTillsResult - GetTillsReply
class GetTillsResponse
  attr_accessor :getTillsResult

  def initialize(getTillsResult = nil)
    @getTillsResult = getTillsResult
  end
end
