#!/usr/bin/env ruby
# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require_relative 'SalesWebService2Driver.rb'

endpoint_url = ARGV.shift
obj = ISalesWebService2.new(endpoint_url)

# run ruby with -d to see SOAP wiredumps.
obj.wiredump_dev = STDERR if $DEBUG

# SYNOPSIS
#   getCurrentBusinessDate(parameters)
#
# ARGS
#   parameters      GetCurrentBusinessDate - {http://www.brinksoftware.com/webservices/sales/v2}GetCurrentBusinessDate
#
# RETURNS
#   parameters      GetCurrentBusinessDateResponse - {http://www.brinksoftware.com/webservices/sales/v2}GetCurrentBusinessDateResponse
#
parameters = nil
puts obj.getCurrentBusinessDate(parameters)

# SYNOPSIS
#   getDeposits(parameters)
#
# ARGS
#   parameters      GetDeposits - {http://www.brinksoftware.com/webservices/sales/v2}GetDeposits
#
# RETURNS
#   parameters      GetDepositsResponse - {http://www.brinksoftware.com/webservices/sales/v2}GetDepositsResponse
#
parameters = nil
puts obj.getDeposits(parameters)

# SYNOPSIS
#   getFutureDateOrderDeposits(parameters)
#
# ARGS
#   parameters      GetFutureDateOrderDeposits - {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrderDeposits
#
# RETURNS
#   parameters      GetFutureDateOrderDepositsResponse - {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrderDepositsResponse
#
parameters = nil
puts obj.getFutureDateOrderDeposits(parameters)

# SYNOPSIS
#   getFutureDateOrders(parameters)
#
# ARGS
#   parameters      GetFutureDateOrders - {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrders
#
# RETURNS
#   parameters      GetFutureDateOrdersResponse - {http://www.brinksoftware.com/webservices/sales/v2}GetFutureDateOrdersResponse
#
parameters = nil
puts obj.getFutureDateOrders(parameters)

# SYNOPSIS
#   getOrders(parameters)
#
# ARGS
#   parameters      GetOrders - {http://www.brinksoftware.com/webservices/sales/v2}GetOrders
#
# RETURNS
#   parameters      GetOrdersResponse - {http://www.brinksoftware.com/webservices/sales/v2}GetOrdersResponse
#
parameters = nil
puts obj.getOrders(parameters)

# SYNOPSIS
#   getTills(parameters)
#
# ARGS
#   parameters      GetTills - {http://www.brinksoftware.com/webservices/sales/v2}GetTills
#
# RETURNS
#   parameters      GetTillsResponse - {http://www.brinksoftware.com/webservices/sales/v2}GetTillsResponse
#
parameters = nil
puts obj.getTills(parameters)


