# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.3)
require 'xsd/qname'

module Brink; module Api


# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfCashDrawer
class ArrayOfCashDrawer < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}CashDrawer
#   defaultBank - SOAP::SOAPDecimal
#   drawerNumber - SOAP::SOAPUnsignedByte
#   id - SOAP::SOAPInt
#   isCompulsory - SOAP::SOAPBoolean
#   isPublic - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   terminalId - SOAP::SOAPInt
#   type - SOAP::SOAPInt
class CashDrawer
  attr_accessor :defaultBank
  attr_accessor :drawerNumber
  attr_accessor :id
  attr_accessor :isCompulsory
  attr_accessor :isPublic
  attr_accessor :name
  attr_accessor :terminalId
  attr_accessor :type

  def initialize(defaultBank = nil, drawerNumber = nil, id = nil, isCompulsory = nil, isPublic = nil, name = nil, terminalId = nil, type = nil)
    @defaultBank = defaultBank
    @drawerNumber = drawerNumber
    @id = id
    @isCompulsory = isCompulsory
    @isPublic = isPublic
    @name = name
    @terminalId = terminalId
    @type = type
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfDayPart
class ArrayOfDayPart < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}DayPart
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   startTime - SOAP::SOAPDateTime
class DayPart
  attr_accessor :id
  attr_accessor :name
  attr_accessor :startTime

  def initialize(id = nil, name = nil, startTime = nil)
    @id = id
    @name = name
    @startTime = startTime
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfDestination
class ArrayOfDestination < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Destination
#   description - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   kitchenDescription - SOAP::SOAPString
#   name - SOAP::SOAPString
class Destination
  attr_accessor :description
  attr_accessor :id
  attr_accessor :kitchenDescription
  attr_accessor :name

  def initialize(description = nil, id = nil, kitchenDescription = nil, name = nil)
    @description = description
    @id = id
    @kitchenDescription = kitchenDescription
    @name = name
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfDiscount
class ArrayOfDiscount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Discount
#   active - SOAP::SOAPBoolean
#   allowLaterDiscounts - SOAP::SOAPBoolean
#   allowPriorDiscounts - SOAP::SOAPBoolean
#   amount - SOAP::SOAPDecimal
#   discountedItemsEligible - SOAP::SOAPBoolean
#   eligibleItemGroupIds - Brink::Api::ArrayOfint
#   eligibleItemId - SOAP::SOAPInt
#   endDate - SOAP::SOAPDateTime
#   endTime - SOAP::SOAPDateTime
#   enforceMaximumAmount - SOAP::SOAPBoolean
#   enforceMaximumItems - SOAP::SOAPBoolean
#   enforceMaximumPerOrder - SOAP::SOAPBoolean
#   excludeItemsFromProductMix - SOAP::SOAPBoolean
#   friday - SOAP::SOAPBoolean
#   granularity - Brink::Api::DiscountGranularity
#   id - SOAP::SOAPInt
#   isEmployeeDiscount - SOAP::SOAPBoolean
#   isLoyaltyDiscount - SOAP::SOAPBoolean
#   managerNeeded - SOAP::SOAPBoolean
#   maximumAmount - SOAP::SOAPDecimal
#   maximumItems - SOAP::SOAPInt
#   maximumPerOrder - SOAP::SOAPInt
#   monday - SOAP::SOAPBoolean
#   mustEnterAmount - SOAP::SOAPBoolean
#   mustEnterName - SOAP::SOAPBoolean
#   mustEnterPercent - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   openDrawer - SOAP::SOAPBoolean
#   printOrder - SOAP::SOAPBoolean
#   printedName - SOAP::SOAPString
#   rate - SOAP::SOAPDecimal
#   saturday - SOAP::SOAPBoolean
#   startDate - SOAP::SOAPDateTime
#   startTime - SOAP::SOAPDateTime
#   sunday - SOAP::SOAPBoolean
#   thursday - SOAP::SOAPBoolean
#   tuesday - SOAP::SOAPBoolean
#   type - Brink::Api::DiscountType
#   useDateRangeFilter - SOAP::SOAPBoolean
#   useDayFilter - SOAP::SOAPBoolean
#   useItemFilter - SOAP::SOAPBoolean
#   useItemGroupFilter - SOAP::SOAPBoolean
#   useTimeRangeFilter - SOAP::SOAPBoolean
#   wednesday - SOAP::SOAPBoolean
class Discount
  attr_accessor :active
  attr_accessor :allowLaterDiscounts
  attr_accessor :allowPriorDiscounts
  attr_accessor :amount
  attr_accessor :discountedItemsEligible
  attr_accessor :eligibleItemGroupIds
  attr_accessor :eligibleItemId
  attr_accessor :endDate
  attr_accessor :endTime
  attr_accessor :enforceMaximumAmount
  attr_accessor :enforceMaximumItems
  attr_accessor :enforceMaximumPerOrder
  attr_accessor :excludeItemsFromProductMix
  attr_accessor :friday
  attr_accessor :granularity
  attr_accessor :id
  attr_accessor :isEmployeeDiscount
  attr_accessor :isLoyaltyDiscount
  attr_accessor :managerNeeded
  attr_accessor :maximumAmount
  attr_accessor :maximumItems
  attr_accessor :maximumPerOrder
  attr_accessor :monday
  attr_accessor :mustEnterAmount
  attr_accessor :mustEnterName
  attr_accessor :mustEnterPercent
  attr_accessor :name
  attr_accessor :openDrawer
  attr_accessor :printOrder
  attr_accessor :printedName
  attr_accessor :rate
  attr_accessor :saturday
  attr_accessor :startDate
  attr_accessor :startTime
  attr_accessor :sunday
  attr_accessor :thursday
  attr_accessor :tuesday
  attr_accessor :type
  attr_accessor :useDateRangeFilter
  attr_accessor :useDayFilter
  attr_accessor :useItemFilter
  attr_accessor :useItemGroupFilter
  attr_accessor :useTimeRangeFilter
  attr_accessor :wednesday

  def initialize(active = nil, allowLaterDiscounts = nil, allowPriorDiscounts = nil, amount = nil, discountedItemsEligible = nil, eligibleItemGroupIds = nil, eligibleItemId = nil, endDate = nil, endTime = nil, enforceMaximumAmount = nil, enforceMaximumItems = nil, enforceMaximumPerOrder = nil, excludeItemsFromProductMix = nil, friday = nil, granularity = nil, id = nil, isEmployeeDiscount = nil, isLoyaltyDiscount = nil, managerNeeded = nil, maximumAmount = nil, maximumItems = nil, maximumPerOrder = nil, monday = nil, mustEnterAmount = nil, mustEnterName = nil, mustEnterPercent = nil, name = nil, openDrawer = nil, printOrder = nil, printedName = nil, rate = nil, saturday = nil, startDate = nil, startTime = nil, sunday = nil, thursday = nil, tuesday = nil, type = nil, useDateRangeFilter = nil, useDayFilter = nil, useItemFilter = nil, useItemGroupFilter = nil, useTimeRangeFilter = nil, wednesday = nil)
    @active = active
    @allowLaterDiscounts = allowLaterDiscounts
    @allowPriorDiscounts = allowPriorDiscounts
    @amount = amount
    @discountedItemsEligible = discountedItemsEligible
    @eligibleItemGroupIds = eligibleItemGroupIds
    @eligibleItemId = eligibleItemId
    @endDate = endDate
    @endTime = endTime
    @enforceMaximumAmount = enforceMaximumAmount
    @enforceMaximumItems = enforceMaximumItems
    @enforceMaximumPerOrder = enforceMaximumPerOrder
    @excludeItemsFromProductMix = excludeItemsFromProductMix
    @friday = friday
    @granularity = granularity
    @id = id
    @isEmployeeDiscount = isEmployeeDiscount
    @isLoyaltyDiscount = isLoyaltyDiscount
    @managerNeeded = managerNeeded
    @maximumAmount = maximumAmount
    @maximumItems = maximumItems
    @maximumPerOrder = maximumPerOrder
    @monday = monday
    @mustEnterAmount = mustEnterAmount
    @mustEnterName = mustEnterName
    @mustEnterPercent = mustEnterPercent
    @name = name
    @openDrawer = openDrawer
    @printOrder = printOrder
    @printedName = printedName
    @rate = rate
    @saturday = saturday
    @startDate = startDate
    @startTime = startTime
    @sunday = sunday
    @thursday = thursday
    @tuesday = tuesday
    @type = type
    @useDateRangeFilter = useDateRangeFilter
    @useDayFilter = useDayFilter
    @useItemFilter = useItemFilter
    @useItemGroupFilter = useItemGroupFilter
    @useTimeRangeFilter = useTimeRangeFilter
    @wednesday = wednesday
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfEmployee
class ArrayOfEmployee < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Employee
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   birthDate - SOAP::SOAPDateTime
#   cellPhone - SOAP::SOAPString
#   city - SOAP::SOAPString
#   emailAddress - SOAP::SOAPString
#   firstName - SOAP::SOAPString
#   hireDate - SOAP::SOAPDateTime
#   homePhone - SOAP::SOAPString
#   id - SOAP::SOAPInt
#   identificationVerified - SOAP::SOAPBoolean
#   jobs - Brink::Api::EmployeeJobs
#   lastName - SOAP::SOAPString
#   maritalStatus - Brink::Api::MaritalStatus
#   middleName - SOAP::SOAPString
#   name - SOAP::SOAPString
#   notes - SOAP::SOAPString
#   payrollId - SOAP::SOAPString
#   sSN - SOAP::SOAPString
#   state - SOAP::SOAPString
#   taxWithholdingAllowance - SOAP::SOAPInt
#   terminated - SOAP::SOAPBoolean
#   terminationDate - SOAP::SOAPDateTime
#   zip - SOAP::SOAPString
class Employee
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :birthDate
  attr_accessor :cellPhone
  attr_accessor :city
  attr_accessor :emailAddress
  attr_accessor :firstName
  attr_accessor :hireDate
  attr_accessor :homePhone
  attr_accessor :id
  attr_accessor :identificationVerified
  attr_accessor :jobs
  attr_accessor :lastName
  attr_accessor :maritalStatus
  attr_accessor :middleName
  attr_accessor :name
  attr_accessor :notes
  attr_accessor :payrollId
  attr_accessor :sSN
  attr_accessor :state
  attr_accessor :taxWithholdingAllowance
  attr_accessor :terminated
  attr_accessor :terminationDate
  attr_accessor :zip

  def initialize(address1 = nil, address2 = nil, birthDate = nil, cellPhone = nil, city = nil, emailAddress = nil, firstName = nil, hireDate = nil, homePhone = nil, id = nil, identificationVerified = nil, jobs = nil, lastName = nil, maritalStatus = nil, middleName = nil, name = nil, notes = nil, payrollId = nil, sSN = nil, state = nil, taxWithholdingAllowance = nil, terminated = nil, terminationDate = nil, zip = nil)
    @address1 = address1
    @address2 = address2
    @birthDate = birthDate
    @cellPhone = cellPhone
    @city = city
    @emailAddress = emailAddress
    @firstName = firstName
    @hireDate = hireDate
    @homePhone = homePhone
    @id = id
    @identificationVerified = identificationVerified
    @jobs = jobs
    @lastName = lastName
    @maritalStatus = maritalStatus
    @middleName = middleName
    @name = name
    @notes = notes
    @payrollId = payrollId
    @sSN = sSN
    @state = state
    @taxWithholdingAllowance = taxWithholdingAllowance
    @terminated = terminated
    @terminationDate = terminationDate
    @zip = zip
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}EmployeeJobs
class EmployeeJobs < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}EmployeeJob
#   jobId - SOAP::SOAPInt
#   payRate - SOAP::SOAPDecimal
#   securityLevelId - SOAP::SOAPInt
class EmployeeJob
  attr_accessor :jobId
  attr_accessor :payRate
  attr_accessor :securityLevelId

  def initialize(jobId = nil, payRate = nil, securityLevelId = nil)
    @jobId = jobId
    @payRate = payRate
    @securityLevelId = securityLevelId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfItemGroup
class ArrayOfItemGroup < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}SettingsObject
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
class SettingsObject
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name

  def initialize(id = nil, isDeleted = nil, name = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ItemGroup
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   alternateId - SOAP::SOAPString
#   items - Brink::Api::ArrayOfItemGroupItem
class ItemGroup < SettingsObject
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :alternateId
  attr_accessor :items

  def initialize(id = nil, isDeleted = nil, name = nil, alternateId = nil, items = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @alternateId = alternateId
    @items = items
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Item
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   active - SOAP::SOAPBoolean
#   askName - SOAP::SOAPBoolean
#   askPrice - SOAP::SOAPBoolean
#   availableFriday - SOAP::SOAPBoolean
#   availableMonday - SOAP::SOAPBoolean
#   availableSaturday - SOAP::SOAPBoolean
#   availableSelectDates - SOAP::SOAPBoolean
#   availableSelectDays - SOAP::SOAPBoolean
#   availableSunday - SOAP::SOAPBoolean
#   availableThursday - SOAP::SOAPBoolean
#   availableTuesday - SOAP::SOAPBoolean
#   availableWednesday - SOAP::SOAPBoolean
#   brandAllocations - Brink::Api::ArrayOfBrandAllocation
#   components - Brink::Api::ArrayOfItemCompositeComponent
#   cost - SOAP::SOAPDecimal
#   createdTime - SOAP::SOAPDateTime
#   datesAvailable - Brink::Api::DateRange
#   giftCardItemType - Brink::Api::GiftCardItemType
#   includedModifiers - Brink::Api::ArrayOfItemIncludedModifier
#   ingredientItemIds - Brink::Api::ArrayOfint
#   isCombo - SOAP::SOAPBoolean
#   isGiftCard - SOAP::SOAPBoolean
#   isQuantityCounted - SOAP::SOAPBoolean
#   itemType - Brink::Api::ItemType
#   kitchenName - SOAP::SOAPString
#   lastEditedTime - SOAP::SOAPDateTime
#   modifierGroupIds - Brink::Api::ArrayOfint
#   modifierTierId - SOAP::SOAPInt
#   modifierWeight - SOAP::SOAPUnsignedByte
#   nonRevenueItem - SOAP::SOAPBoolean
#   pLU - SOAP::SOAPString
#   price - SOAP::SOAPDecimal
#   priceLevel - SOAP::SOAPUnsignedByte
#   pricePer - Brink::Api::PricePer
#   printerGroupId - SOAP::SOAPInt
#   revenueCenterId - SOAP::SOAPInt
#   sortPriority - SOAP::SOAPUnsignedByte
#   tareId - SOAP::SOAPInt
#   taxIds - Brink::Api::ArrayOfint
#   unitName - SOAP::SOAPString
#   unitPrecision - SOAP::SOAPUnsignedByte
#   videoGroupId - SOAP::SOAPInt
class Item < SettingsObject
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :active
  attr_accessor :askName
  attr_accessor :askPrice
  attr_accessor :availableFriday
  attr_accessor :availableMonday
  attr_accessor :availableSaturday
  attr_accessor :availableSelectDates
  attr_accessor :availableSelectDays
  attr_accessor :availableSunday
  attr_accessor :availableThursday
  attr_accessor :availableTuesday
  attr_accessor :availableWednesday
  attr_accessor :brandAllocations
  attr_accessor :components
  attr_accessor :cost
  attr_accessor :createdTime
  attr_accessor :datesAvailable
  attr_accessor :giftCardItemType
  attr_accessor :includedModifiers
  attr_accessor :ingredientItemIds
  attr_accessor :isCombo
  attr_accessor :isGiftCard
  attr_accessor :isQuantityCounted
  attr_accessor :itemType
  attr_accessor :kitchenName
  attr_accessor :lastEditedTime
  attr_accessor :modifierGroupIds
  attr_accessor :modifierTierId
  attr_accessor :modifierWeight
  attr_accessor :nonRevenueItem
  attr_accessor :pLU
  attr_accessor :price
  attr_accessor :priceLevel
  attr_accessor :pricePer
  attr_accessor :printerGroupId
  attr_accessor :revenueCenterId
  attr_accessor :sortPriority
  attr_accessor :tareId
  attr_accessor :taxIds
  attr_accessor :unitName
  attr_accessor :unitPrecision
  attr_accessor :videoGroupId

  def initialize(id = nil, isDeleted = nil, name = nil, active = nil, askName = nil, askPrice = nil, availableFriday = nil, availableMonday = nil, availableSaturday = nil, availableSelectDates = nil, availableSelectDays = nil, availableSunday = nil, availableThursday = nil, availableTuesday = nil, availableWednesday = nil, brandAllocations = nil, components = nil, cost = nil, createdTime = nil, datesAvailable = nil, giftCardItemType = nil, includedModifiers = nil, ingredientItemIds = nil, isCombo = nil, isGiftCard = nil, isQuantityCounted = nil, itemType = nil, kitchenName = nil, lastEditedTime = nil, modifierGroupIds = nil, modifierTierId = nil, modifierWeight = nil, nonRevenueItem = nil, pLU = nil, price = nil, priceLevel = nil, pricePer = nil, printerGroupId = nil, revenueCenterId = nil, sortPriority = nil, tareId = nil, taxIds = nil, unitName = nil, unitPrecision = nil, videoGroupId = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @active = active
    @askName = askName
    @askPrice = askPrice
    @availableFriday = availableFriday
    @availableMonday = availableMonday
    @availableSaturday = availableSaturday
    @availableSelectDates = availableSelectDates
    @availableSelectDays = availableSelectDays
    @availableSunday = availableSunday
    @availableThursday = availableThursday
    @availableTuesday = availableTuesday
    @availableWednesday = availableWednesday
    @brandAllocations = brandAllocations
    @components = components
    @cost = cost
    @createdTime = createdTime
    @datesAvailable = datesAvailable
    @giftCardItemType = giftCardItemType
    @includedModifiers = includedModifiers
    @ingredientItemIds = ingredientItemIds
    @isCombo = isCombo
    @isGiftCard = isGiftCard
    @isQuantityCounted = isQuantityCounted
    @itemType = itemType
    @kitchenName = kitchenName
    @lastEditedTime = lastEditedTime
    @modifierGroupIds = modifierGroupIds
    @modifierTierId = modifierTierId
    @modifierWeight = modifierWeight
    @nonRevenueItem = nonRevenueItem
    @pLU = pLU
    @price = price
    @priceLevel = priceLevel
    @pricePer = pricePer
    @printerGroupId = printerGroupId
    @revenueCenterId = revenueCenterId
    @sortPriority = sortPriority
    @tareId = tareId
    @taxIds = taxIds
    @unitName = unitName
    @unitPrecision = unitPrecision
    @videoGroupId = videoGroupId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}LoyaltyReward
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   isActive - SOAP::SOAPBoolean
#   type - SOAP::SOAPUnsignedByte
class LoyaltyReward < SettingsObject
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :isActive
  attr_accessor :type

  def initialize(id = nil, isDeleted = nil, name = nil, isActive = nil, type = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @isActive = isActive
    @type = type
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}DiscountReward
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   isActive - SOAP::SOAPBoolean
#   type - SOAP::SOAPUnsignedByte
#   discountId - SOAP::SOAPInt
class DiscountReward < LoyaltyReward
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :isActive
  attr_accessor :type
  attr_accessor :discountId

  def initialize(id = nil, isDeleted = nil, name = nil, isActive = nil, type = nil, discountId = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @isActive = isActive
    @type = type
    @discountId = discountId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GiftCardReward
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   isActive - SOAP::SOAPBoolean
#   type - SOAP::SOAPUnsignedByte
#   amount - SOAP::SOAPDecimal
class GiftCardReward < LoyaltyReward
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :isActive
  attr_accessor :type
  attr_accessor :amount

  def initialize(id = nil, isDeleted = nil, name = nil, isActive = nil, type = nil, amount = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @isActive = isActive
    @type = type
    @amount = amount
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}PromotionReward
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   isActive - SOAP::SOAPBoolean
#   type - SOAP::SOAPUnsignedByte
#   promotionId - SOAP::SOAPInt
class PromotionReward < LoyaltyReward
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :isActive
  attr_accessor :type
  attr_accessor :promotionId

  def initialize(id = nil, isDeleted = nil, name = nil, isActive = nil, type = nil, promotionId = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @isActive = isActive
    @type = type
    @promotionId = promotionId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}VoucherReward
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   isActive - SOAP::SOAPBoolean
#   type - SOAP::SOAPUnsignedByte
class VoucherReward < LoyaltyReward
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :isActive
  attr_accessor :type

  def initialize(id = nil, isDeleted = nil, name = nil, isActive = nil, type = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @isActive = isActive
    @type = type
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ModifierCode
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   abbreviation - SOAP::SOAPString
#   active - SOAP::SOAPBoolean
#   appliesTo - Brink::Api::ModCodeIngredientType
#   isSystem - SOAP::SOAPBoolean
#   type - Brink::Api::ModCodeType
class ModifierCode < SettingsObject
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :abbreviation
  attr_accessor :active
  attr_accessor :appliesTo
  attr_accessor :isSystem
  attr_accessor :type

  def initialize(id = nil, isDeleted = nil, name = nil, abbreviation = nil, active = nil, appliesTo = nil, isSystem = nil, type = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @abbreviation = abbreviation
    @active = active
    @appliesTo = appliesTo
    @isSystem = isSystem
    @type = type
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ModifierGroup
#   id - SOAP::SOAPInt
#   isDeleted - SOAP::SOAPBoolean
#   name - SOAP::SOAPString
#   description - SOAP::SOAPString
#   displayName - SOAP::SOAPString
#   flowRequired - SOAP::SOAPBoolean
#   free - SOAP::SOAPUnsignedByte
#   items - Brink::Api::ArrayOfModifierGroupItem
#   maximum - SOAP::SOAPUnsignedByte
#   minimum - SOAP::SOAPUnsignedByte
#   panelId - SOAP::SOAPInt
class ModifierGroup < SettingsObject
  attr_accessor :id
  attr_accessor :isDeleted
  attr_accessor :name
  attr_accessor :description
  attr_accessor :displayName
  attr_accessor :flowRequired
  attr_accessor :free
  attr_accessor :items
  attr_accessor :maximum
  attr_accessor :minimum
  attr_accessor :panelId

  def initialize(id = nil, isDeleted = nil, name = nil, description = nil, displayName = nil, flowRequired = nil, free = nil, items = nil, maximum = nil, minimum = nil, panelId = nil)
    @id = id
    @isDeleted = isDeleted
    @name = name
    @description = description
    @displayName = displayName
    @flowRequired = flowRequired
    @free = free
    @items = items
    @maximum = maximum
    @minimum = minimum
    @panelId = panelId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfItemGroupItem
class ArrayOfItemGroupItem < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ItemGroupItem
#   itemId - SOAP::SOAPInt
class ItemGroupItem
  attr_accessor :itemId

  def initialize(itemId = nil)
    @itemId = itemId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfItem
class ArrayOfItem < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfItemCompositeComponent
class ArrayOfItemCompositeComponent < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ItemCompositeComponent
#   id - SOAP::SOAPInt
#   itemGroupId - SOAP::SOAPInt
#   items - Brink::Api::ArrayOfItemCompositeComponentItem
#   name - SOAP::SOAPString
#   overridePrice - SOAP::SOAPBoolean
#   price - SOAP::SOAPDecimal
#   rollupPrice - SOAP::SOAPBoolean
class ItemCompositeComponent
  attr_accessor :id
  attr_accessor :itemGroupId
  attr_accessor :items
  attr_accessor :name
  attr_accessor :overridePrice
  attr_accessor :price
  attr_accessor :rollupPrice

  def initialize(id = nil, itemGroupId = nil, items = nil, name = nil, overridePrice = nil, price = nil, rollupPrice = nil)
    @id = id
    @itemGroupId = itemGroupId
    @items = items
    @name = name
    @overridePrice = overridePrice
    @price = price
    @rollupPrice = rollupPrice
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfItemCompositeComponentItem
class ArrayOfItemCompositeComponentItem < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ItemCompositeComponentItem
#   id - SOAP::SOAPInt
#   isDefault - SOAP::SOAPBoolean
#   itemId - SOAP::SOAPInt
#   overridePrice - SOAP::SOAPBoolean
#   price - SOAP::SOAPDecimal
class ItemCompositeComponentItem
  attr_accessor :id
  attr_accessor :isDefault
  attr_accessor :itemId
  attr_accessor :overridePrice
  attr_accessor :price

  def initialize(id = nil, isDefault = nil, itemId = nil, overridePrice = nil, price = nil)
    @id = id
    @isDefault = isDefault
    @itemId = itemId
    @overridePrice = overridePrice
    @price = price
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfItemIncludedModifier
class ArrayOfItemIncludedModifier < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ItemIncludedModifier
#   automaticallyAdd - SOAP::SOAPBoolean
#   isIncluded - SOAP::SOAPBoolean
#   itemId - SOAP::SOAPInt
#   modifierGroupId - SOAP::SOAPInt
#   position - SOAP::SOAPShort
#   printInKitchen - SOAP::SOAPBoolean
class ItemIncludedModifier
  attr_accessor :automaticallyAdd
  attr_accessor :isIncluded
  attr_accessor :itemId
  attr_accessor :modifierGroupId
  attr_accessor :position
  attr_accessor :printInKitchen

  def initialize(automaticallyAdd = nil, isIncluded = nil, itemId = nil, modifierGroupId = nil, position = nil, printInKitchen = nil)
    @automaticallyAdd = automaticallyAdd
    @isIncluded = isIncluded
    @itemId = itemId
    @modifierGroupId = modifierGroupId
    @position = position
    @printInKitchen = printInKitchen
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfJob
class ArrayOfJob < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Job
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
class Job
  attr_accessor :id
  attr_accessor :name

  def initialize(id = nil, name = nil)
    @id = id
    @name = name
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfLoyaltyReward
class ArrayOfLoyaltyReward < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfModifierCode
class ArrayOfModifierCode < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfModifierGroup
class ArrayOfModifierGroup < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfModifierGroupItem
class ArrayOfModifierGroupItem < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ModifierGroupItem
#   itemId - SOAP::SOAPInt
#   position - SOAP::SOAPShort
#   price - SOAP::SOAPDecimal
#   priceMethod - SOAP::SOAPUnsignedByte
class ModifierGroupItem
  attr_accessor :itemId
  attr_accessor :position
  attr_accessor :price
  attr_accessor :priceMethod

  def initialize(itemId = nil, position = nil, price = nil, priceMethod = nil)
    @itemId = itemId
    @position = position
    @price = price
    @priceMethod = priceMethod
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Options
#   accounting - Brink::Api::AccountingOptions
#   location - Brink::Api::LocationOptions
class Options
  attr_accessor :accounting
  attr_accessor :location

  def initialize(accounting = nil, location = nil)
    @accounting = accounting
    @location = location
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}AccountingOptions
#   gLExport - Brink::Api::GLExport
class AccountingOptions
  attr_accessor :gLExport

  def initialize(gLExport = nil)
    @gLExport = gLExport
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExport
#   discounts - Brink::Api::ArrayOfGLExportDiscountAccount
#   name - SOAP::SOAPString
#   others - Brink::Api::ArrayOfGLExportOtherAccount
#   pettyAccounts - Brink::Api::ArrayOfGLExportPettyAccount
#   promotions - Brink::Api::ArrayOfGLExportPromotionAccount
#   revenueCenters - Brink::Api::ArrayOfGLExportRevenueCenterAccount
#   surcharges - Brink::Api::ArrayOfGLExportSurchargeAccount
#   taxes - Brink::Api::ArrayOfGLExportTaxAccount
#   tenders - Brink::Api::ArrayOfGLExportTenderAccount
#   tendersForEcommerce - Brink::Api::ArrayOfGLExportTenderAccount
class GLExport
  attr_accessor :discounts
  attr_accessor :name
  attr_accessor :others
  attr_accessor :pettyAccounts
  attr_accessor :promotions
  attr_accessor :revenueCenters
  attr_accessor :surcharges
  attr_accessor :taxes
  attr_accessor :tenders
  attr_accessor :tendersForEcommerce

  def initialize(discounts = nil, name = nil, others = nil, pettyAccounts = nil, promotions = nil, revenueCenters = nil, surcharges = nil, taxes = nil, tenders = nil, tendersForEcommerce = nil)
    @discounts = discounts
    @name = name
    @others = others
    @pettyAccounts = pettyAccounts
    @promotions = promotions
    @revenueCenters = revenueCenters
    @surcharges = surcharges
    @taxes = taxes
    @tenders = tenders
    @tendersForEcommerce = tendersForEcommerce
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportDiscountAccount
class ArrayOfGLExportDiscountAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
class GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportDiscountAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   discountId - SOAP::SOAPInt
class GLExportDiscountAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :discountId

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, discountId = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @discountId = discountId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportOtherAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   type - SOAP::SOAPInt
class GLExportOtherAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :type

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, type = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @type = type
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportPettyAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   pettyAccountId - SOAP::SOAPInt
class GLExportPettyAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :pettyAccountId

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, pettyAccountId = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @pettyAccountId = pettyAccountId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportPromotionAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   promotionId - SOAP::SOAPInt
class GLExportPromotionAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :promotionId

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, promotionId = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @promotionId = promotionId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportRevenueCenterAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   revenueCenterId - SOAP::SOAPInt
class GLExportRevenueCenterAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :revenueCenterId

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, revenueCenterId = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @revenueCenterId = revenueCenterId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportSurchargeAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   surchargeId - SOAP::SOAPInt
class GLExportSurchargeAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :surchargeId

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, surchargeId = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @surchargeId = surchargeId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportTaxAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   taxId - SOAP::SOAPInt
class GLExportTaxAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :taxId

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, taxId = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @taxId = taxId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}GLExportTenderAccount
#   m_class - SOAP::SOAPString
#   creditAccount - SOAP::SOAPString
#   debitAccount - SOAP::SOAPString
#   memo - SOAP::SOAPString
#   name - SOAP::SOAPString
#   tenderId - SOAP::SOAPInt
class GLExportTenderAccount < GLExportAccount
  attr_accessor :creditAccount
  attr_accessor :debitAccount
  attr_accessor :memo
  attr_accessor :name
  attr_accessor :tenderId

  def m_class
    @v_class
  end

  def m_class=(value)
    @v_class = value
  end

  def initialize(v_class = nil, creditAccount = nil, debitAccount = nil, memo = nil, name = nil, tenderId = nil)
    @v_class = v_class
    @creditAccount = creditAccount
    @debitAccount = debitAccount
    @memo = memo
    @name = name
    @tenderId = tenderId
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportOtherAccount
class ArrayOfGLExportOtherAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportPettyAccount
class ArrayOfGLExportPettyAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportPromotionAccount
class ArrayOfGLExportPromotionAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportRevenueCenterAccount
class ArrayOfGLExportRevenueCenterAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportSurchargeAccount
class ArrayOfGLExportSurchargeAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportTaxAccount
class ArrayOfGLExportTaxAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfGLExportTenderAccount
class ArrayOfGLExportTenderAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}LocationOptions
#   address1 - SOAP::SOAPString
#   address2 - SOAP::SOAPString
#   city - SOAP::SOAPString
#   country - SOAP::SOAPString
#   fax - SOAP::SOAPString
#   latitude - SOAP::SOAPDecimal
#   longitude - SOAP::SOAPDecimal
#   name - SOAP::SOAPString
#   phone - SOAP::SOAPString
#   state - SOAP::SOAPString
#   timeZone - Brink::Api::TimeZone
#   zip - SOAP::SOAPString
class LocationOptions
  attr_accessor :address1
  attr_accessor :address2
  attr_accessor :city
  attr_accessor :country
  attr_accessor :fax
  attr_accessor :latitude
  attr_accessor :longitude
  attr_accessor :name
  attr_accessor :phone
  attr_accessor :state
  attr_accessor :timeZone
  attr_accessor :zip

  def initialize(address1 = nil, address2 = nil, city = nil, country = nil, fax = nil, latitude = nil, longitude = nil, name = nil, phone = nil, state = nil, timeZone = nil, zip = nil)
    @address1 = address1
    @address2 = address2
    @city = city
    @country = country
    @fax = fax
    @latitude = latitude
    @longitude = longitude
    @name = name
    @phone = phone
    @state = state
    @timeZone = timeZone
    @zip = zip
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfPettyAccount
class ArrayOfPettyAccount < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}PettyAccount
#   accountType - Brink::Api::PettyAccountType
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
class PettyAccount
  attr_accessor :accountType
  attr_accessor :id
  attr_accessor :name

  def initialize(accountType = nil, id = nil, name = nil)
    @accountType = accountType
    @id = id
    @name = name
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfPromotion
class ArrayOfPromotion < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Promotion
#   active - SOAP::SOAPBoolean
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   type - Brink::Api::PromotionType
class Promotion
  attr_accessor :active
  attr_accessor :id
  attr_accessor :name
  attr_accessor :type

  def initialize(active = nil, id = nil, name = nil, type = nil)
    @active = active
    @id = id
    @name = name
    @type = type
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfRegister
class ArrayOfRegister < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Register
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   number - SOAP::SOAPInt
class Register
  attr_accessor :id
  attr_accessor :name
  attr_accessor :number

  def initialize(id = nil, name = nil, number = nil)
    @id = id
    @name = name
    @number = number
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfRevenueCenter
class ArrayOfRevenueCenter < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}RevenueCenter
#   active - SOAP::SOAPBoolean
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   taxIds - Brink::Api::ArrayOfint
class RevenueCenter
  attr_accessor :active
  attr_accessor :id
  attr_accessor :name
  attr_accessor :taxIds

  def initialize(active = nil, id = nil, name = nil, taxIds = nil)
    @active = active
    @id = id
    @name = name
    @taxIds = taxIds
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfSection
class ArrayOfSection < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Section
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
class Section
  attr_accessor :id
  attr_accessor :name

  def initialize(id = nil, name = nil)
    @id = id
    @name = name
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfSurcharge
class ArrayOfSurcharge < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Surcharge
#   amount - SOAP::SOAPDecimal
#   automaticallyApply - SOAP::SOAPBoolean
#   days - SOAP::SOAPInt
#   endDate - SOAP::SOAPDateTime
#   endTime - SOAP::SOAPDateTime
#   enforceDateRanges - SOAP::SOAPBoolean
#   enforceDays - SOAP::SOAPBoolean
#   enforcePartySize - SOAP::SOAPBoolean
#   enforceTimeRanges - SOAP::SOAPBoolean
#   id - SOAP::SOAPInt
#   limitDestinations - SOAP::SOAPBoolean
#   limitSections - SOAP::SOAPBoolean
#   maximumPartySize - SOAP::SOAPInt
#   method - SOAP::SOAPInt
#   minimumPartySize - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   prompt - SOAP::SOAPBoolean
#   startDate - SOAP::SOAPDateTime
#   startTime - SOAP::SOAPDateTime
#   taxIds - Brink::Api::ArrayOfint
#   terminalTypes - SOAP::SOAPInt
#   type - SOAP::SOAPInt
#   validDestinationIds - Brink::Api::ArrayOfint
#   validSectionIds - Brink::Api::ArrayOfint
class Surcharge
  attr_accessor :amount
  attr_accessor :automaticallyApply
  attr_accessor :days
  attr_accessor :endDate
  attr_accessor :endTime
  attr_accessor :enforceDateRanges
  attr_accessor :enforceDays
  attr_accessor :enforcePartySize
  attr_accessor :enforceTimeRanges
  attr_accessor :id
  attr_accessor :limitDestinations
  attr_accessor :limitSections
  attr_accessor :maximumPartySize
  attr_accessor :method
  attr_accessor :minimumPartySize
  attr_accessor :name
  attr_accessor :prompt
  attr_accessor :startDate
  attr_accessor :startTime
  attr_accessor :taxIds
  attr_accessor :terminalTypes
  attr_accessor :type
  attr_accessor :validDestinationIds
  attr_accessor :validSectionIds

  def initialize(amount = nil, automaticallyApply = nil, days = nil, endDate = nil, endTime = nil, enforceDateRanges = nil, enforceDays = nil, enforcePartySize = nil, enforceTimeRanges = nil, id = nil, limitDestinations = nil, limitSections = nil, maximumPartySize = nil, method = nil, minimumPartySize = nil, name = nil, prompt = nil, startDate = nil, startTime = nil, taxIds = nil, terminalTypes = nil, type = nil, validDestinationIds = nil, validSectionIds = nil)
    @amount = amount
    @automaticallyApply = automaticallyApply
    @days = days
    @endDate = endDate
    @endTime = endTime
    @enforceDateRanges = enforceDateRanges
    @enforceDays = enforceDays
    @enforcePartySize = enforcePartySize
    @enforceTimeRanges = enforceTimeRanges
    @id = id
    @limitDestinations = limitDestinations
    @limitSections = limitSections
    @maximumPartySize = maximumPartySize
    @method = method
    @minimumPartySize = minimumPartySize
    @name = name
    @prompt = prompt
    @startDate = startDate
    @startTime = startTime
    @taxIds = taxIds
    @terminalTypes = terminalTypes
    @type = type
    @validDestinationIds = validDestinationIds
    @validSectionIds = validSectionIds
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfTax
class ArrayOfTax < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Tax
#   amount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
#   type - SOAP::SOAPInt
class Tax
  attr_accessor :amount
  attr_accessor :id
  attr_accessor :name
  attr_accessor :type

  def initialize(amount = nil, id = nil, name = nil, type = nil)
    @amount = amount
    @id = id
    @name = name
    @type = type
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfTender
class ArrayOfTender < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}Tender
#   active - SOAP::SOAPBoolean
#   allowChange - SOAP::SOAPBoolean
#   allowTips - SOAP::SOAPBoolean
#   cardType - Brink::Api::CardType
#   defaultAmount - SOAP::SOAPDecimal
#   id - SOAP::SOAPInt
#   maxTipPercent - SOAP::SOAPDecimal
#   maximumAccountDigits - SOAP::SOAPByte
#   minimumAccountDigits - SOAP::SOAPByte
#   name - SOAP::SOAPString
#   openDrawer - SOAP::SOAPBoolean
#   reconciliationMethod - Brink::Api::ReconciliationMethod
#   requiresAuthorization - SOAP::SOAPBoolean
#   signatureCapture - SOAP::SOAPBoolean
#   tenderType - Brink::Api::TenderType
#   varianceAmount - SOAP::SOAPDecimal
class Tender
  attr_accessor :active
  attr_accessor :allowChange
  attr_accessor :allowTips
  attr_accessor :cardType
  attr_accessor :defaultAmount
  attr_accessor :id
  attr_accessor :maxTipPercent
  attr_accessor :maximumAccountDigits
  attr_accessor :minimumAccountDigits
  attr_accessor :name
  attr_accessor :openDrawer
  attr_accessor :reconciliationMethod
  attr_accessor :requiresAuthorization
  attr_accessor :signatureCapture
  attr_accessor :tenderType
  attr_accessor :varianceAmount

  def initialize(active = nil, allowChange = nil, allowTips = nil, cardType = nil, defaultAmount = nil, id = nil, maxTipPercent = nil, maximumAccountDigits = nil, minimumAccountDigits = nil, name = nil, openDrawer = nil, reconciliationMethod = nil, requiresAuthorization = nil, signatureCapture = nil, tenderType = nil, varianceAmount = nil)
    @active = active
    @allowChange = allowChange
    @allowTips = allowTips
    @cardType = cardType
    @defaultAmount = defaultAmount
    @id = id
    @maxTipPercent = maxTipPercent
    @maximumAccountDigits = maximumAccountDigits
    @minimumAccountDigits = minimumAccountDigits
    @name = name
    @openDrawer = openDrawer
    @reconciliationMethod = reconciliationMethod
    @requiresAuthorization = requiresAuthorization
    @signatureCapture = signatureCapture
    @tenderType = tenderType
    @varianceAmount = varianceAmount
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}ArrayOfVoidReason
class ArrayOfVoidReason < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}VoidReason
#   id - SOAP::SOAPInt
#   name - SOAP::SOAPString
class VoidReason
  attr_accessor :id
  attr_accessor :name

  def initialize(id = nil, name = nil)
    @id = id
    @name = name
  end
end

# {http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfint
class ArrayOfint < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos}ArrayOfBrandAllocation
class ArrayOfBrandAllocation < ::Array
end

# {http://schemas.datacontract.org/2004/07/Pos}BrandAllocation
#   brandId - SOAP::SOAPInt
#   id - SOAP::SOAPInt
#   weight - SOAP::SOAPDecimal
class BrandAllocation
  attr_accessor :brandId
  attr_accessor :id
  attr_accessor :weight

  def initialize(brandId = nil, id = nil, weight = nil)
    @brandId = brandId
    @id = id
    @weight = weight
  end
end

# {http://schemas.datacontract.org/2004/07/Brink.Foundation}DateRange
#   m_end - SOAP::SOAPDateTime
#   start - SOAP::SOAPDateTime
class DateRange
  attr_accessor :start

  def m_end
    @v_end
  end

  def m_end=(value)
    @v_end = value
  end

  def initialize(v_end = nil, start = nil)
    @v_end = v_end
    @start = start
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessFault
#   code - Brink::Api::AccessErrorCode
#   message - SOAP::SOAPString
class AccessFault < ::StandardError
  attr_accessor :code
  attr_accessor :message

  def initialize(code = nil, message = nil)
    @code = code
    @message = message
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationFault
#   code - Brink::Api::LocationErrorCode
#   message - SOAP::SOAPString
class LocationFault < ::StandardError
  attr_accessor :code
  attr_accessor :message

  def initialize(code = nil, message = nil)
    @code = code
    @message = message
  end
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Data}TimeZone
class TimeZone < ::String
  Alaska = new("Alaska")
  Arizona = new("Arizona")
  Central = new("Central")
  Eastern = new("Eastern")
  GeorgetownLaPazManausSanJuan = new("GeorgetownLaPazManausSanJuan")
  Hawaii = new("Hawaii")
  Mountain = new("Mountain")
  Pacific = new("Pacific")
end

# {http://schemas.datacontract.org/2004/07/Pos}DiscountGranularity
class DiscountGranularity < ::String
  Items = new("Items")
  Order = new("Order")
end

# {http://schemas.datacontract.org/2004/07/Pos}DiscountType
class DiscountType < ::String
  Comp = new("Comp")
  Max = new("Max")
  NewPrice = new("NewPrice")
  None = new("None")
end

# {http://schemas.datacontract.org/2004/07/Pos}MaritalStatus
class MaritalStatus < ::String
  Married = new("Married")
  None = new("None")
  Single = new("Single")
end

# {http://schemas.datacontract.org/2004/07/Pos}GiftCardItemType
class GiftCardItemType < ::String
  CashOut = new("CashOut")
  Issue = new("Issue")
  None = new("None")
  Reload = new("Reload")
end

# {http://schemas.datacontract.org/2004/07/Pos}ItemType
class ItemType < ::String
  Chicken = new("Chicken")
  Composite = new("Composite")
  GiftCard = new("GiftCard")
  LoyaltyItem = new("LoyaltyItem")
  Normal = new("Normal")
  Pizza = new("Pizza")
  Prepaid = new("Prepaid")
end

# {http://schemas.datacontract.org/2004/07/Pos}PricePer
class PricePer < ::String
  Ounce = new("Ounce")
  Pound = new("Pound")
end

# {http://schemas.datacontract.org/2004/07/Pos}ModCodeIngredientType
class ModCodeIngredientType < ::String
  Both = new("Both")
  Ingredients = new("Ingredients")
  NonIngredients = new("NonIngredients")
end

# {http://schemas.datacontract.org/2004/07/Pos}ModCodeType
class ModCodeType < ::String
  For = new("For")
  No = new("No")
  Normal = new("Normal")
  OnSide = new("OnSide")
  Sub = new("Sub")
end

# {http://schemas.datacontract.org/2004/07/Pos}PettyAccountType
class PettyAccountType < ::String
  CashIn = new("CashIn")
  CashOut = new("CashOut")
end

# {http://schemas.datacontract.org/2004/07/Pos}PromotionType
class PromotionType < ::String
  Bogo = new("Bogo")
  Combo = new("Combo")
  Coupon = new("Coupon")
  GiftCard = new("GiftCard")
  Max = new("Max")
  None = new("None")
  OrderReduction = new("OrderReduction")
end

# {http://schemas.datacontract.org/2004/07/Pos}ReconciliationMethod
class ReconciliationMethod < ::String
  Details = new("Details")
  Totals = new("Totals")
end

# {http://schemas.datacontract.org/2004/07/Pos}TenderType
class TenderType < ::String
  Cash = new("Cash")
  Check = new("Check")
  CreditCard = new("CreditCard")
  Debit = new("Debit")
  External = new("External")
  GiftCard = new("GiftCard")
  GiftCertificate = new("GiftCertificate")
  HouseAccount = new("HouseAccount")
  None = new("None")
end

# {http://schemas.datacontract.org/2004/07/Brink.Credit}CardType
class CardType < ::String
  AmericanExpress = new("AmericanExpress")
  Diners = new("Diners")
  Discover = new("Discover")
  EnRoute = new("enRoute")
  JCB = new("JCB")
  MasterCard = new("MasterCard")
  None = new("None")
  Private = new("Private")
  Visa = new("Visa")
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}AccessErrorCode
class AccessErrorCode < ::String
  AccessDenied = new("AccessDenied")
  InvalidToken = new("InvalidToken")
end

# {http://schemas.datacontract.org/2004/07/Pos.Web.Service.Faults}LocationErrorCode
class LocationErrorCode < ::String
  Disabled = new("Disabled")
  InvalidToken = new("InvalidToken")
end

# {http://tempuri.org/}GetCashDrawers
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetCashDrawers
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetCashDrawersResponse
#   getCashDrawersResult - Brink::Api::ArrayOfCashDrawer
class GetCashDrawersResponse
  attr_accessor :getCashDrawersResult

  def initialize(getCashDrawersResult = nil)
    @getCashDrawersResult = getCashDrawersResult
  end
end

# {http://tempuri.org/}GetDayParts
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetDayParts
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetDayPartsResponse
#   getDayPartsResult - Brink::Api::ArrayOfDayPart
class GetDayPartsResponse
  attr_accessor :getDayPartsResult

  def initialize(getDayPartsResult = nil)
    @getDayPartsResult = getDayPartsResult
  end
end

# {http://tempuri.org/}GetDestinations
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetDestinations
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetDestinationsResponse
#   getDestinationsResult - Brink::Api::ArrayOfDestination
class GetDestinationsResponse
  attr_accessor :getDestinationsResult

  def initialize(getDestinationsResult = nil)
    @getDestinationsResult = getDestinationsResult
  end
end

# {http://tempuri.org/}GetDiscounts
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetDiscounts
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetDiscountsResponse
#   getDiscountsResult - Brink::Api::ArrayOfDiscount
class GetDiscountsResponse
  attr_accessor :getDiscountsResult

  def initialize(getDiscountsResult = nil)
    @getDiscountsResult = getDiscountsResult
  end
end

# {http://tempuri.org/}GetEmployees
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetEmployees
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetEmployeesResponse
#   getEmployeesResult - Brink::Api::ArrayOfEmployee
class GetEmployeesResponse
  attr_accessor :getEmployeesResult

  def initialize(getEmployeesResult = nil)
    @getEmployeesResult = getEmployeesResult
  end
end

# {http://tempuri.org/}GetItemGroups
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetItemGroups
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetItemGroupsResponse
#   getItemGroupsResult - Brink::Api::ArrayOfItemGroup
class GetItemGroupsResponse
  attr_accessor :getItemGroupsResult

  def initialize(getItemGroupsResult = nil)
    @getItemGroupsResult = getItemGroupsResult
  end
end

# {http://tempuri.org/}GetItems
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetItems
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetItemsResponse
#   getItemsResult - Brink::Api::ArrayOfItem
class GetItemsResponse
  attr_accessor :getItemsResult

  def initialize(getItemsResult = nil)
    @getItemsResult = getItemsResult
  end
end

# {http://tempuri.org/}GetJobs
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetJobs
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetJobsResponse
#   getJobsResult - Brink::Api::ArrayOfJob
class GetJobsResponse
  attr_accessor :getJobsResult

  def initialize(getJobsResult = nil)
    @getJobsResult = getJobsResult
  end
end

# {http://tempuri.org/}GetLoyaltyRewards
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetLoyaltyRewards
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetLoyaltyRewardsResponse
#   getLoyaltyRewardsResult - Brink::Api::ArrayOfLoyaltyReward
class GetLoyaltyRewardsResponse
  attr_accessor :getLoyaltyRewardsResult

  def initialize(getLoyaltyRewardsResult = nil)
    @getLoyaltyRewardsResult = getLoyaltyRewardsResult
  end
end

# {http://tempuri.org/}GetModifierCodes
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetModifierCodes
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetModifierCodesResponse
#   getModifierCodesResult - Brink::Api::ArrayOfModifierCode
class GetModifierCodesResponse
  attr_accessor :getModifierCodesResult

  def initialize(getModifierCodesResult = nil)
    @getModifierCodesResult = getModifierCodesResult
  end
end

# {http://tempuri.org/}GetModifierGroups
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetModifierGroups
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetModifierGroupsResponse
#   getModifierGroupsResult - Brink::Api::ArrayOfModifierGroup
class GetModifierGroupsResponse
  attr_accessor :getModifierGroupsResult

  def initialize(getModifierGroupsResult = nil)
    @getModifierGroupsResult = getModifierGroupsResult
  end
end

# {http://tempuri.org/}GetOptions
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetOptions
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetOptionsResponse
#   getOptionsResult - Brink::Api::Options
class GetOptionsResponse
  attr_accessor :getOptionsResult

  def initialize(getOptionsResult = nil)
    @getOptionsResult = getOptionsResult
  end
end

# {http://tempuri.org/}GetPettyAccounts
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetPettyAccounts
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetPettyAccountsResponse
#   getPettyAccountsResult - Brink::Api::ArrayOfPettyAccount
class GetPettyAccountsResponse
  attr_accessor :getPettyAccountsResult

  def initialize(getPettyAccountsResult = nil)
    @getPettyAccountsResult = getPettyAccountsResult
  end
end

# {http://tempuri.org/}GetPromotions
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetPromotions
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetPromotionsResponse
#   getPromotionsResult - Brink::Api::ArrayOfPromotion
class GetPromotionsResponse
  attr_accessor :getPromotionsResult

  def initialize(getPromotionsResult = nil)
    @getPromotionsResult = getPromotionsResult
  end
end

# {http://tempuri.org/}GetRegisters
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetRegisters
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetRegistersResponse
#   getRegistersResult - Brink::Api::ArrayOfRegister
class GetRegistersResponse
  attr_accessor :getRegistersResult

  def initialize(getRegistersResult = nil)
    @getRegistersResult = getRegistersResult
  end
end

# {http://tempuri.org/}GetRevenueCenters
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetRevenueCenters
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetRevenueCentersResponse
#   getRevenueCentersResult - Brink::Api::ArrayOfRevenueCenter
class GetRevenueCentersResponse
  attr_accessor :getRevenueCentersResult

  def initialize(getRevenueCentersResult = nil)
    @getRevenueCentersResult = getRevenueCentersResult
  end
end

# {http://tempuri.org/}GetSections
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetSections
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetSectionsResponse
#   getSectionsResult - Brink::Api::ArrayOfSection
class GetSectionsResponse
  attr_accessor :getSectionsResult

  def initialize(getSectionsResult = nil)
    @getSectionsResult = getSectionsResult
  end
end

# {http://tempuri.org/}GetSurcharges
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetSurcharges
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetSurchargesResponse
#   getSurchargesResult - Brink::Api::ArrayOfSurcharge
class GetSurchargesResponse
  attr_accessor :getSurchargesResult

  def initialize(getSurchargesResult = nil)
    @getSurchargesResult = getSurchargesResult
  end
end

# {http://tempuri.org/}GetTaxes
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetTaxes
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetTaxesResponse
#   getTaxesResult - Brink::Api::ArrayOfTax
class GetTaxesResponse
  attr_accessor :getTaxesResult

  def initialize(getTaxesResult = nil)
    @getTaxesResult = getTaxesResult
  end
end

# {http://tempuri.org/}GetTenders
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetTenders
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetTendersResponse
#   getTendersResult - Brink::Api::ArrayOfTender
class GetTendersResponse
  attr_accessor :getTendersResult

  def initialize(getTendersResult = nil)
    @getTendersResult = getTendersResult
  end
end

# {http://tempuri.org/}GetVoidReasons
#   accessToken - SOAP::SOAPString
#   locationToken - SOAP::SOAPString
class GetVoidReasons
  attr_accessor :accessToken
  attr_accessor :locationToken

  def initialize(accessToken = nil, locationToken = nil)
    @accessToken = accessToken
    @locationToken = locationToken
  end
end

# {http://tempuri.org/}GetVoidReasonsResponse
#   getVoidReasonsResult - Brink::Api::ArrayOfVoidReason
class GetVoidReasonsResponse
  attr_accessor :getVoidReasonsResult

  def initialize(getVoidReasonsResult = nil)
    @getVoidReasonsResult = getVoidReasonsResult
  end
end


end; end
